namespace: lootlog-prod
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: prod-afcb02cae41c2bc395316f3ffae8a9c2a5cca83a
namePrefix: prod-
