namespace: lootlog-prod
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: prod-e81868a06449ab396398c330df047bf504dd8ca1
namePrefix: prod-
