namespace: lootlog-prod
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: prod-f9a7a12692b3343573b41513180501c3172afa41
namePrefix: prod-
