namespace: lootlog-dev
resources:
  - ../../base/activity
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-activity
    newTag: dev-da3023c2d4cae21d91522559f77effdbb5ebbfa4
namePrefix: dev-
