/** Shared transport definitions for the battlelog HTTP contract. */
import * as Schema from "effect/Schema";
import { DateTimeString, FiniteNumber } from "@lootlog/schema/http-scalars";

const BattleWarriorResponse = Schema.Struct({
  id: Schema.String,
  battleId: Schema.String,
  originalId: Schema.String,
  name: Schema.String,
  lvl: FiniteNumber,
  prof: Schema.String,
  icon: Schema.String,
  team: FiniteNumber,
  turns: FiniteNumber,
  turnsLost: FiniteNumber,
  steps: FiniteNumber,
  normalAttacks: FiniteNumber,
  spellsUsed: FiniteNumber,
  spellsUsedMap: Schema.Record(Schema.String, FiniteNumber),
  isDead: Schema.Boolean,
  surrendered: Schema.Boolean,
  fled: Schema.Boolean,
  maxHp: FiniteNumber,
  damageDealt: FiniteNumber,
  distanceDamage: FiniteNumber,
  meleeDamage: FiniteNumber,
  auxiliaryDamage: FiniteNumber,
  fireDamage: FiniteNumber,
  frostDamage: FiniteNumber,
  lightningDamage: FiniteNumber,
  thirdAttDamage: FiniteNumber,
  damageDealtAfterDefensive: FiniteNumber,
  damageDealtAfterDefensivePercentage: FiniteNumber,
  damageTaken: FiniteNumber,
  distanceDamageTaken: FiniteNumber,
  meleeDamageTaken: FiniteNumber,
  auxiliaryDamageTaken: FiniteNumber,
  fireDamageTaken: FiniteNumber,
  frostDamageTaken: FiniteNumber,
  lightningDamageTaken: FiniteNumber,
  thirdAttDamageTaken: FiniteNumber,
  flatDamageTaken: FiniteNumber,
  rageDamageDealt: FiniteNumber,
  trueDamageDealt: FiniteNumber,
  trueDamageTaken: FiniteNumber,
  stigmaDamageDealt: FiniteNumber,
  stigmaDamageTaken: FiniteNumber,
  passiveHealing: FiniteNumber,
  activeHealing: FiniteNumber,
  armorPierces: FiniteNumber,
  criticalHits: FiniteNumber,
  reducedArmor: FiniteNumber,
  reducedPoisonResistance: FiniteNumber,
  magicResistanceDestroyed: FiniteNumber,
  evasions: FiniteNumber,
  attacksEvaded: FiniteNumber,
  counters: FiniteNumber,
  fastArrows: FiniteNumber,
  blocks: FiniteNumber,
  attacksBlocked: FiniteNumber,
  blockedDamage: FiniteNumber,
  woundDamageTaken: FiniteNumber,
  poisonDamageTaken: FiniteNumber,
  injureDamageTaken: FiniteNumber,
  injures: FiniteNumber,
  critWoundDamageTaken: FiniteNumber,
  firePassiveDamageTaken: FiniteNumber,
  lightningPassiveDamageTaken: FiniteNumber,
  destroyedEnergy: FiniteNumber,
  destroyedMana: FiniteNumber,
  regeneratedEnergy: FiniteNumber,
  regeneratedMana: FiniteNumber,
  reflectedDamage: FiniteNumber,
  reflectedDamageTaken: FiniteNumber,
  legbons: FiniteNumber,
  legbonCurse: FiniteNumber,
  legbonCleanse: FiniteNumber,
  legbonLastheal: FiniteNumber,
  legbonLasthealValue: FiniteNumber,
  legbonGlare: FiniteNumber,
  legbonHolytouch: FiniteNumber,
  legbonHolytouchValue: FiniteNumber,
  legbonCritredValue: FiniteNumber,
  legbonFacadeValue: FiniteNumber,
  legbonPunctureValue: FiniteNumber,
  legbonVerycrit: FiniteNumber,
  legbonAnguish: FiniteNumber,
  legbonAnguishDamageTaken: FiniteNumber,
  ph: FiniteNumber,
});

const BattleTimelineDeltas = Schema.Struct({
  damageDealt: FiniteNumber,
  damageTaken: FiniteNumber,
  healingDone: FiniteNumber,
  healingReceived: FiniteNumber,
  mitigation: FiniteNumber,
  resourceDelta: FiniteNumber,
  resourcePressure: FiniteNumber,
  energyPressure: FiniteNumber,
  manaPressure: FiniteNumber,
  absorbGained: FiniteNumber,
  absorbSpent: FiniteNumber,
  magicAbsorbGained: FiniteNumber,
  magicAbsorbSpent: FiniteNumber,
  controlApplied: FiniteNumber,
  controlTaken: FiniteNumber,
});

const NullableBattleStatisticEntry = Schema.Union([
  Schema.StructWithRest(
    Schema.Struct({
      warriorId: Schema.String,
      name: Schema.String,
      value: FiniteNumber,
      formattedValue: Schema.optionalKey(Schema.String),
    }),
    [
      Schema.Record(
        Schema.String,
        Schema.Json.annotate({ expected: "JSON value" }),
      ),
    ],
  ),
  Schema.Null,
]);

export type BattleTimelineResponseDto_Output =
  typeof BattleTimelineResponseDto_Output.Type;

export const BattleTimelineResponseDto_Output = Schema.Struct({
  battleId: Schema.String,
  generatedAt: DateTimeString,
  timeline: Schema.Array(
    Schema.Struct({
      turn: FiniteNumber,
      attackerId: Schema.Union([Schema.String, Schema.Null]),
      defenderId: Schema.Union([Schema.String, Schema.Null]),
      attackerHpPercentage: Schema.Union([FiniteNumber, Schema.Null]),
      defenderHpPercentage: Schema.Union([FiniteNumber, Schema.Null]),
      hpByWarrior: Schema.Record(Schema.String, FiniteNumber),
      teamHp: Schema.Record(Schema.String, FiniteNumber),
      teamHpDelta: Schema.Record(Schema.String, FiniteNumber),
      deltas: Schema.Struct({
        damage: FiniteNumber,
        healing: FiniteNumber,
        mitigation: FiniteNumber,
        resourcePressure: FiniteNumber,
        energyPressure: FiniteNumber,
        manaPressure: FiniteNumber,
        byWarrior: Schema.Record(Schema.String, BattleTimelineDeltas),
      }),
      cumulative: Schema.Record(Schema.String, BattleTimelineDeltas),
      actions: Schema.Array(
        Schema.Struct({
          actionType: Schema.String,
          param: Schema.String,
          category: Schema.String,
          actorId: Schema.Union([Schema.String, Schema.Null]),
          targetId: Schema.Union([Schema.String, Schema.Null]),
          value: FiniteNumber,
          handled: Schema.Boolean,
        }),
      ),
      flags: Schema.Array(Schema.String),
      labels: Schema.Array(Schema.String),
      significanceScore: FiniteNumber,
      reason: Schema.String,
    }),
  ),
  warriors: Schema.Array(BattleWarriorResponse),
}).annotate({ identifier: "BattleTimelineResponseDto_Output" });

export const BattleResponseFields = {
  id: Schema.String,
  createdAt: DateTimeString,
  updatedAt: DateTimeString,
  public: Schema.Boolean,
  userId: Schema.String,
  accountId: Schema.String,
  characterId: Schema.String,
  world: Schema.String,
  duration: FiniteNumber,
  type: Schema.String,
  winner: Schema.String,
  loser: Schema.String,
  winningTeam: FiniteNumber,
  losingTeam: FiniteNumber,
  honorPoints: FiniteNumber,
  hasFlee: Schema.Boolean,
  matchmaking: Schema.Boolean,
  statistics: Schema.Struct({
    topDamageDealer: NullableBattleStatisticEntry,
    topTank: NullableBattleStatisticEntry,
    bestEfficiency: NullableBattleStatisticEntry,
    criticalMaster: NullableBattleStatisticEntry,
    evasionExpert: NullableBattleStatisticEntry,
    shieldWall: NullableBattleStatisticEntry,
    damagePerTurn: NullableBattleStatisticEntry,
    mostActive: NullableBattleStatisticEntry,
    legendaryWarrior: NullableBattleStatisticEntry,
    untouchable: NullableBattleStatisticEntry,
  }),
  difficultyRank: Schema.Union([FiniteNumber, Schema.Null]),
  result: Schema.Union([FiniteNumber, Schema.Null]),
  ratingDelta: Schema.Union([FiniteNumber, Schema.Null]),
  opponentLvl: Schema.Union([FiniteNumber, Schema.Null]),
  opponentOplvl: Schema.Union([FiniteNumber, Schema.Null]),
  opponentRating: Schema.Union([FiniteNumber, Schema.Null]),
  rating: Schema.Union([FiniteNumber, Schema.Null]),
  status: Schema.Union([FiniteNumber, Schema.Null]),
  pointsGained: Schema.Union([FiniteNumber, Schema.Null]),
  placementCur: Schema.Union([FiniteNumber, Schema.Null]),
  placementMax: Schema.Union([FiniteNumber, Schema.Null]),
  dailyStageId: Schema.Union([FiniteNumber, Schema.Null]),
  dailyPointsCur: Schema.Union([FiniteNumber, Schema.Null]),
  dailyPointsMax: Schema.Union([FiniteNumber, Schema.Null]),
  dailyPointsStep: Schema.Union([FiniteNumber, Schema.Null]),
  dailyRewardsLast: Schema.Union([FiniteNumber, Schema.Null]),
  dailyRewardsCur: Schema.Union([FiniteNumber, Schema.Null]),
  dailyRewardsMax: Schema.Union([FiniteNumber, Schema.Null]),
  warriors: Schema.Array(BattleWarriorResponse),
};

export type BattleResponseDto_Output = typeof BattleResponseDto_Output.Type;

export const BattleResponseDto_Output = Schema.Struct(
  BattleResponseFields,
).annotate({ identifier: "BattleResponseDto_Output" });

export type BattleRawResponseDto_Output =
  typeof BattleRawResponseDto_Output.Type;

export const BattleRawResponseDto_Output = Schema.Struct({
  battleId: Schema.String,
  timestamp: DateTimeString,
  rawData: Schema.Struct({
    accountId: Schema.String,
    characterId: Schema.String,
    world: Schema.String,
    events: Schema.Array(
      Schema.Struct({
        attackerId: Schema.Union([Schema.String, Schema.Null]),
        defenderId: Schema.Union([Schema.String, Schema.Null]),
        attackerHpPercentage: Schema.Union([FiniteNumber, Schema.Null]),
        defenderHpPercentage: Schema.Union([FiniteNumber, Schema.Null]),
        actions: Schema.Array(
          Schema.Struct({ actionType: Schema.String, param: Schema.String }),
        ),
      }),
    ),
    sourceEvents: Schema.optionalKey(
      Schema.Array(Schema.Json.annotate({ expected: "JSON value" })),
    ),
  }),
}).annotate({ identifier: "BattleRawResponseDto_Output" });

export const BattlePagination = Schema.Struct({
  size: FiniteNumber,
  hasNext: Schema.Boolean,
  hasPrev: Schema.Boolean,
  nextCursor: Schema.optionalKey(Schema.String),
  previousCursor: Schema.optionalKey(Schema.String),
  total: Schema.optionalKey(FiniteNumber),
});
