export enum Queue {
  // guilds
  GUILDS_SYNC = 'backend-guilds-sync',
  GUILDS_SYNC_DLQ = 'backend-guilds-sync.dlq',
  GUILDS_SYNC_RETRY = 'backend-guilds-sync.retry',
  GUILDS_CREATE = 'backend-guilds-create',
  GUILDS_CREATE_DLQ = 'backend-guilds-create.dlq',
  GUILDS_CREATE_RETRY = 'backend-guilds-create.retry',
  GUILDS_DELETE = 'backend-guilds-delete',
  GUILDS_DELETE_DLQ = 'backend-guilds-delete.dlq',
  GUILDS_DELETE_RETRY = 'backend-guilds-delete.retry',
  GUILDS_UPDATE = 'backend-guilds-update',
  GUILDS_UPDATE_DLQ = 'backend-guilds-update.dlq',
  GUILDS_UPDATE_RETRY = 'backend-guilds-update.retry',
  GUILDS_INITIALIZE = 'backend-guilds-initialize',
  GUILDS_INITIALIZE_DLQ = 'backend-guilds-initialize.dlq',
  GUILDS_INITIALIZE_RETRY = 'backend-guilds-initialize.retry',
  GUILDS_RPC_GET_USER_GUILDS = 'backend-guilds-rpc-get-user-guilds',
  // roles
  GUILDS_CREATE_ROLE = 'backend-guilds-create-role',
  GUILDS_CREATE_ROLE_DLQ = 'backend-guilds-create-role.dlq',
  GUILDS_CREATE_ROLE_RETRY = 'backend-guilds-create-role.retry',
  GUILDS_UPDATE_ROLE = 'backend-guilds-update-role',
  GUILDS_UPDATE_ROLE_DLQ = 'backend-guilds-update-role.dlq',
  GUILDS_UPDATE_ROLE_RETRY = 'backend-guilds-update-role.retry',
  GUILDS_DELETE_ROLE = 'backend-guilds-delete-role',
  GUILDS_DELETE_ROLE_DLQ = 'backend-guilds-delete-role.dlq',
  GUILDS_DELETE_ROLE_RETRY = 'backend-guilds-delete-role.retry',
  // members
  GUILDS_MEMBERS_ADD = 'backend-guilds-members-add',
  GUILDS_MEMBERS_ADD_DLQ = 'backend-guilds-members-add.dlq',
  GUILDS_MEMBERS_ADD_RETRY = 'backend-guilds-members-add.retry',
  GUILDS_MEMBERS_REMOVE = 'backend-guilds-members-remove',
  GUILDS_MEMBERS_REMOVE_DLQ = 'backend-guilds-members-remove.dlq',
  GUILDS_MEMBERS_REMOVE_RETRY = 'backend-guilds-members-remove.retry',
  GUILDS_MEMBERS_UPDATE = 'backend-guilds-members-update',
  GUILDS_MEMBERS_UPDATE_DLQ = 'backend-guilds-members-update.dlq',
  GUILDS_MEMBERS_UPDATE_RETRY = 'backend-guilds-members-update.retry',
  GUILDS_MEMBERS_ADD_ROLE = 'backend-guilds-members-add-role',
  GUILDS_MEMBERS_ADD_ROLE_DLQ = 'backend-guilds-members-add-role.dlq',
  GUILDS_MEMBERS_ADD_ROLE_RETRY = 'backend-guilds-members-add-role.retry',
  GUILDS_MEMBERS_REMOVE_ROLE = 'backend-guilds-members-remove-role',
  GUILDS_MEMBERS_REMOVE_ROLE_DLQ = 'backend-guilds-members-remove-role.dlq',
  GUILDS_MEMBERS_REMOVE_ROLE_RETRY = 'backend-guilds-members-remove-role.retry',
}
