export enum RoutingKey {
  GUILDS_SEND_MESSAGE = "guilds.send.message",

  GUILDS_LOOTS_CREATE = "guilds.loots.create",
  GUILDS_LOOTS_SHARE_UPDATE = "guilds.loots.share.update",

  GUILDS_TIMERS_UPDATE = "guilds.timers.update",
  GUILDS_TIMERS_DELETE = "guilds.timers.delete",

  GUILDS_RESERVATIONS_CREATE = "guilds.reservations.create",
  GUILDS_RESERVATIONS_DELETE = "guilds.reservations.delete",

  GUILDS_NOTIFICATIONS_SEND = "guilds.notifications.send",
  GUILDS_NOTIFICATIONS_VOLUNTEER = "guilds.notifications.volunteer",
  GUILDS_PARTY_GATHERING = "guilds.party-gathering",
  GUILDS_PARTY_GATHERING_CANCEL = "guilds.party-gathering.cancel",
  USERS_PARTY_READY_ROOM_UPDATED = "users.party-ready-room.updated",
  NOTIFICATIONS_TIMER_UPDATED = "notifications.timer.updated",
  NOTIFICATIONS_TIMER_DELETED = "notifications.timer.deleted",
  NOTIFICATIONS_LOOT_CREATED = "notifications.loot.created",
  NOTIFICATIONS_DISCORD_SEND = "notifications.discord.send",
  NOTIFICATIONS_DELIVERY_RESULT = "notifications.delivery.result",
  DISCORD_GUILD_CHANNELS_SYNCED = "discord.guild.channels.synced",
  DISCORD_GUILD_CHANNELS_SYNC_FAILED = "discord.guild.channels.sync.failed",
  DISCORD_GUILD_CHANNEL_UPSERTED = "discord.guild.channel.upserted",
  DISCORD_GUILD_CHANNEL_DELETED = "discord.guild.channel.deleted",
  DISCORD_GUILD_SYNC_STATE_UPDATED = "discord.guild.sync-state.updated",

  GUILDS_DELETE_MESSAGE = "guilds.delete.message",
  GUILDS_UPDATE_MESSAGE = "guilds.update.message",
  GUILDS_CLEAR_MESSAGES = "guilds.clear.messages",

  GUILDS_MEMBERS_ADD = "guilds.members.add",
  GUILDS_MEMBERS_REMOVE = "guilds.members.remove",
  GUILDS_MEMBERS_UPDATE = "guilds.members.update",
  GUILDS_MEMBERS_ADD_ROLE = "guilds.members.add.role",
  GUILDS_MEMBERS_REMOVE_ROLE = "guilds.members.remove.role",

  GUILDS_CREATE = "guilds.create",
  GUILDS_SYNC = "guilds.sync",
  GUILDS_SYNC_TRIGGER = "guilds.sync.trigger",
  GUILDS_CREATE_DLQ = "guilds.create.dlq",
  GUILDS_CREATE_RETRY = "guilds.create.retry",
  GUILDS_UPDATE = "guilds.update",
  GUILDS_UPDATE_DLQ = "guilds.update.dlq",
  GUILDS_UPDATE_RETRY = "guilds.update.retry",
  GUILDS_DELETE = "guilds.delete",
  GUILDS_DELETE_DLQ = "guilds.delete.dlq",
  GUILDS_DELETE_RETRY = "guilds.delete.retry",
  GUILDS_INITIALIZE = "guilds.initialize",
  GUILDS_INITIALIZE_DLQ = "guilds.initialize.dlq",
  GUILDS_INITIALIZE_RETRY = "guilds.initialize.retry",

  GUILDS_CREATE_ROLE = "guilds.create.role",
  GUILDS_CREATE_ROLE_DLQ = "guilds.create.role.dlq",
  GUILDS_CREATE_ROLE_RETRY = "guilds.create.role.retry",
  GUILDS_UPDATE_ROLE = "guilds.update.role",
  GUILDS_UPDATE_ROLE_DLQ = "guilds.update.role.dlq",
  GUILDS_UPDATE_ROLE_RETRY = "guilds.update.role.retry",
  GUILDS_DELETE_ROLE = "guilds.delete.role",
  GUILDS_DELETE_ROLE_DLQ = "guilds.delete.role.dlq",
  GUILDS_DELETE_ROLE_RETRY = "guilds.delete.role.retry",

  GUILDS_MEMBERS_ADD_DLQ = "guilds.members.add.dlq",
  GUILDS_MEMBERS_ADD_RETRY = "guilds.members.add.retry",
  GUILDS_MEMBERS_REMOVE_DLQ = "guilds.members.remove.dlq",
  GUILDS_MEMBERS_REMOVE_RETRY = "guilds.members.remove.retry",
  GUILDS_MEMBERS_UPDATE_DLQ = "guilds.members.update.dlq",
  GUILDS_MEMBERS_UPDATE_RETRY = "guilds.members.update.retry",
  GUILDS_MEMBERS_ADD_ROLE_DLQ = "guilds.members.add.role.dlq",
  GUILDS_MEMBERS_ADD_ROLE_RETRY = "guilds.members.add.role.retry",
  GUILDS_MEMBERS_REMOVE_ROLE_DLQ = "guilds.members.remove.role.dlq",
  GUILDS_MEMBERS_REMOVE_ROLE_RETRY = "guilds.members.remove.role.retry",
  GUILDS_MEMBERS_REFRESH_JOB_UPDATE = "guilds.members.refresh.job.update",

  SEARCH_NPCS_INDEX = "search.npcs.index",
  SEARCH_PLAYERS_INDEX = "search.players.index",
  SEARCH_ITEMS_INDEX = "search.items.index",

  ACTIVITY_LOG_CREATE = "activity.log.create",

  EVENT_MAP_STATUS_UPDATE = "event.map-status.update",
  EVENT_HERO_KILLED = "event.hero.killed",
  EVENT_RANKING_UPDATE = "event.ranking.update",
  PRESENCE_COVERAGE_CHECK = "presence.coverage.check",

  EVENT_RESPAWN_WINDOW_OPENED = "event.respawn-window.opened",
  EVENT_RESPAWN_WINDOW_CLOSED = "event.respawn-window.closed",

  PRESENCE_CHECK_REQUEST = "presence.check.request",
}
