export enum RoutingKey {
  GUILDS_SEND_MESSAGE = 'guilds.send.message',

  GUILDS_TIMERS_UPDATE = 'guilds.timers.update',
  GUILDS_TIMERS_DELETE = 'guilds.timers.delete',

  GUILDS_NOTIFICATIONS_SEND = 'guilds.notifications.send',

  GUILDS_MEMBERS_ADD = 'guilds.members.add',
  GUILDS_MEMBERS_REMOVE = 'guilds.members.remove',
  GUILDS_MEMBERS_UPDATE = 'guilds.members.update',
  GUILDS_MEMBERS_ADD_ROLE = 'guilds.members.add.role',
  GUILDS_MEMBERS_REMOVE_ROLE = 'guilds.members.remove.role',

  GUILDS_CREATE = 'guilds.create',
  GUILDS_CREATE_DLQ = 'guilds.create.dlq',
  GUILDS_CREATE_RETRY = 'guilds.create.retry',
  GUILDS_UPDATE = 'guilds.update',
  GUILDS_UPDATE_DLQ = 'guilds.update.dlq',
  GUILDS_UPDATE_RETRY = 'guilds.update.retry',
  GUILDS_DELETE = 'guilds.delete',
  GUILDS_DELETE_DLQ = 'guilds.delete.dlq',
  GUILDS_DELETE_RETRY = 'guilds.delete.retry',
  GUILDS_INITIALIZE = 'guilds.initialize',
  GUILDS_INITIALIZE_DLQ = 'guilds.initialize.dlq',
  GUILDS_INITIALIZE_RETRY = 'guilds.initialize.retry',
  GUILDS_RPC_GET_USER_GUILDS = 'guilds.rpc.get.user-guilds',

  GUILDS_CREATE_ROLE = 'guilds.create.role',
  GUILDS_CREATE_ROLE_DLQ = 'guilds.create.role.dlq',
  GUILDS_CREATE_ROLE_RETRY = 'guilds.create.role.retry',
  GUILDS_UPDATE_ROLE = 'guilds.update.role',
  GUILDS_UPDATE_ROLE_DLQ = 'guilds.update.role.dlq',
  GUILDS_UPDATE_ROLE_RETRY = 'guilds.update.role.retry',
  GUILDS_DELETE_ROLE = 'guilds.delete.role',
  GUILDS_DELETE_ROLE_DLQ = 'guilds.delete.role.dlq',
  GUILDS_DELETE_ROLE_RETRY = 'guilds.delete.role.retry',

  GUILDS_MEMBERS_ADD_DLQ = 'guilds.members.add.dlq',
  GUILDS_MEMBERS_ADD_RETRY = 'guilds.members.add.retry',
  GUILDS_MEMBERS_REMOVE_DLQ = 'guilds.members.remove.dlq',
  GUILDS_MEMBERS_REMOVE_RETRY = 'guilds.members.remove.retry',
  GUILDS_MEMBERS_UPDATE_DLQ = 'guilds.members.update.dlq',
  GUILDS_MEMBERS_UPDATE_RETRY = 'guilds.members.update.retry',
  GUILDS_MEMBERS_ADD_ROLE_DLQ = 'guilds.members.add.role.dlq',
  GUILDS_MEMBERS_ADD_ROLE_RETRY = 'guilds.members.add.role.retry',
  GUILDS_MEMBERS_REMOVE_ROLE_DLQ = 'guilds.members.remove.role.dlq',
  GUILDS_MEMBERS_REMOVE_ROLE_RETRY = 'guilds.members.remove.role.retry',

  SEARCH_NPCS_INDEX = 'search.npcs.index',
  SEARCH_PLAYERS_INDEX = 'search.players.index',
}
