import type { Warrior } from "@lootlog/battle-processor";

export const BATTLE_WARRIOR_STATS_VERSION = 1;

export const BATTLE_WARRIOR_STATS_KEYS = [
  "turns",
  "turnsLost",
  "steps",
  "normalAttacks",
  "spellsUsed",
  "spellsUsedMap",
  "isDead",
  "surrendered",
  "fled",
  "maxHp",
  "damageDealt",
  "distanceDamage",
  "meleeDamage",
  "auxiliaryDamage",
  "fireDamage",
  "frostDamage",
  "lightningDamage",
  "thirdAttDamage",
  "damageDealtAfterDefensive",
  "damageDealtAfterDefensivePercentage",
  "damageTaken",
  "distanceDamageTaken",
  "meleeDamageTaken",
  "auxiliaryDamageTaken",
  "fireDamageTaken",
  "frostDamageTaken",
  "lightningDamageTaken",
  "thirdAttDamageTaken",
  "flatDamageTaken",
  "rageDamageDealt",
  "trueDamageDealt",
  "trueDamageTaken",
  "stigmaDamageDealt",
  "stigmaDamageTaken",
  "passiveHealing",
  "activeHealing",
  "armorPierces",
  "criticalHits",
  "reducedArmor",
  "reducedPoisonResistance",
  "magicResistanceDestroyed",
  "woundDamageTaken",
  "poisonDamageTaken",
  "injureDamageTaken",
  "injures",
  "critWoundDamageTaken",
  "evasions",
  "attacksEvaded",
  "counters",
  "fastArrows",
  "firePassiveDamageTaken",
  "lightningPassiveDamageTaken",
  "destroyedEnergy",
  "destroyedMana",
  "blockedDamage",
  "blocks",
  "attacksBlocked",
  "regeneratedEnergy",
  "regeneratedMana",
  "reflectedDamage",
  "reflectedDamageTaken",
  "legbons",
  "legbonCurse",
  "legbonCleanse",
  "legbonLastheal",
  "legbonLasthealValue",
  "legbonGlare",
  "legbonHolytouch",
  "legbonHolytouchValue",
  "legbonCritredValue",
  "legbonFacadeValue",
  "legbonVerycrit",
  "legbonAnguish",
  "legbonAnguishDamageTaken",
  "legbonPunctureValue",
] as const satisfies readonly (keyof Warrior)[];

export type BattleWarriorStatsKey = (typeof BATTLE_WARRIOR_STATS_KEYS)[number];

export type BattleWarriorStats = Pick<Warrior, BattleWarriorStatsKey>;
