packages:
  - "apps/*"
  - "packages/*"
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
verifyDepsBeforeRun: false
packageExtensions:
  "@hookform/resolvers":
    peerDependencies:
      zod: "*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - cpu-features
  - esbuild
  - msgpackr-extract
  - rolldown
  - prisma
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - workerd
minimumReleaseAgeExclude:
  - esbuild@0.24.3
  - "@hono/node-server@1.19.13"
  - postcss@8.5.10
  - js-cookie@3.0.6
  - esbuild@0.28.1
allowBuilds:
  "@prisma/engines": set this to true or false
  "@scarf/scarf": set this to true or false
  "@sentry/cli": set this to true or false
  "@swc/core": set this to true or false
  cpu-features: set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  necord: set this to true or false
  prisma: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  ssh2: set this to true or false
  workerd: set this to true or false
