/** Explicit supported HTTP inventory. Unknown operations are session-only. */
export type PublicApiService = "main" | "activity" | "battlelog" | "search";
export type PublicApiOperation = {
  readonly service: PublicApiService;
  readonly method: string;
  readonly path: string;
  readonly operationId: string;
  readonly access: "read" | "write" | "session-only";
  readonly data: "organization" | "personal" | "mixed" | "public";
};

export const PUBLIC_API_OPERATIONS = [
  {
    service: "main",
    method: "GET",
    path: "/users/@me/feed",
    operationId: "UsersController_getUserFeed",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/users/@me",
    operationId: "UsersController_deleteAccount",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/preferences",
    operationId: "UsersController_getUserPreferences",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/users/@me/preferences",
    operationId: "UsersController_updateUserPreferences",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/guilds",
    operationId: "UsersController_getCurrentUserGuilds",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/guilds/accessible",
    operationId: "UsersController_getCurrentUserAccessibleGuilds",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/game-preferences/accounts/{accountId}",
    operationId: "UsersController_getUserGameAccountPreferences",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/users/@me/game-preferences/accounts/{accountId}",
    operationId: "UsersController_updateUserGameAccountPreferences",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/@me",
    operationId: "MembersController_getMe",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/members/@me/refresh",
    operationId: "MembersController_refreshMe",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/members/{discordId}/refresh",
    operationId: "MembersController_refreshMember",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/members/{discordId}/deactivate",
    operationId: "MembersController_deactivateMember",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/{discordId}/lootlog-config-summary",
    operationId: "MembersController_getMemberLootlogConfigSummary",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members",
    operationId: "MembersController_getGuildMembers",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/references",
    operationId: "MembersController_getGuildMemberReferences",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/summary",
    operationId: "MembersController_getGuildMembersSummary",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/members/refresh-all",
    operationId: "MembersController_refreshAllMembers",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/refresh-jobs/latest",
    operationId: "MembersController_getLatestRefreshJob",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/members/refresh-jobs/{jobId}",
    operationId: "MembersController_getRefreshJobStatus",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/@me",
    operationId: "GuildsController_getUserGuilds",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/@me/permissions",
    operationId: "GuildsController_getUserGuildsWithPermissions",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/@me/manageable",
    operationId: "GuildsController_getManageableUserGuilds",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}",
    operationId: "GuildsController_getGuildById",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/config",
    operationId: "GuildsController_getGuildConfig",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/config",
    operationId: "GuildsController_updateGuildConfig",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/worlds",
    operationId: "GuildsController_getWorldsByGuildId",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/permissions",
    operationId: "GuildsController_getGuildPermissions",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/discord-sync",
    operationId: "GuildsController_getGuildDiscordSyncStatus",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/discord-sync/refresh",
    operationId: "GuildsController_refreshGuildDiscordSync",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/internal/guilds/user-permissions",
    operationId: "GuildsInternalController_getUserPermissions",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/internal/guilds/{idOrVanityUrl}",
    operationId: "GuildsInternalController_getGuildByIdOrVanityUrl",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/roles",
    operationId: "RolesController_getGuildRoles",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/roles/{roleId}/permissions",
    operationId: "RolesController_updateGuildRole",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/timers",
    operationId: "TimersController_getAllTimers",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/timers/history",
    operationId: "TimersController_getRecentTimerHistory",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/timers",
    operationId: "TimersController_getTimers",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/timers/npcs/search",
    operationId: "TimersController_searchNpcsWithTimerData",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/timers/auto",
    operationId: "TimersController_createAutoTimer",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/timers/{timerIdentifier}/reset",
    operationId: "TimersController_resetTimer",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/timers/{timerIdentifier}",
    operationId: "TimersController_deleteTimer",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/timers/{timerIdentifier}/history",
    operationId: "TimersController_getTimerHistory",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/timers/history/{historyEntryId}/restore",
    operationId: "TimersController_restoreTimerFromHistory",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/timers/manual",
    operationId: "TimersController_createManualTimer",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/lootlog-config/accounts/{accountId}",
    operationId: "UserLootlogConfigController_getUserLootlogConfigByAccountId",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "PUT",
    path: "/users/@me/lootlog-config/accounts/{accountId}",
    operationId:
      "UserLootlogConfigController_createOrUpdateLootlogCharacterConfig",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/lootlog-config/players/catching-guilds/batch",
    operationId: "UserLootlogConfigController_getPlayersCatchingGuilds",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/timer-settings",
    operationId: "TimerSettingsController_getGlobalSettings",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/timer-settings",
    operationId: "TimerSettingsController_updateGlobalSettings",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/timer-settings/guilds/{guildId}",
    operationId: "TimerSettingsController_getGuildSettings",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/timer-settings/guilds/{guildId}",
    operationId: "TimerSettingsController_updateGuildSettings",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/timer-settings/migrate",
    operationId: "TimerSettingsController_migrateSettings",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/preferences",
    operationId: "SettingsDocumentsController_getPreferences",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/preferences",
    operationId: "SettingsDocumentsController_patchPreferences",
    access: "session-only",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots",
    operationId: "LootsController_fetchLootsByGuildId",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots/stats",
    operationId: "LootsController_getLootStats",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots/count",
    operationId: "LootsController_countLootsByGuildId",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots/items/resolve",
    operationId: "LootsController_resolveLootItemByHid",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots/{lootId}",
    operationId: "LootsController_fetchLootById",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/loots/{lootId}",
    operationId: "LootsController_deleteLoot",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/loots",
    operationId: "LootsController_createLoot",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/loots/{lootId}/comments",
    operationId: "LootsController_getComments",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/loots/{lootId}/comments",
    operationId: "LootsController_createComment",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/loots/{id}",
    operationId: "LootsController_updateLoot",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/lootlog-config",
    operationId: "LootlogConfigController_getLootlogConfig",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PUT",
    path: "/guilds/{guildId}/lootlog-config/{npcId}",
    operationId: "LootlogConfigController_updateNpc",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/healthz",
    operationId: "HealthzController_healthCheck",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/chat-messages",
    operationId: "ChatController_getChatMessages",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/chat-messages",
    operationId: "ChatController_sendChatMessage",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/chat-messages",
    operationId: "ChatController_clearChatMessages",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/chat-messages/{messageId}",
    operationId: "ChatController_deleteChatMessage",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/chat-messages/{messageId}",
    operationId: "ChatController_updateChatMessage",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/reservation-spots",
    operationId: "listReservationSpots",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/reservation-spots/{spotId}/reservations",
    operationId: "listSpotReservations",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/reservation-spots/{spotId}/reservations",
    operationId: "createReservation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/reservations/{reservationId}",
    operationId: "deleteReservation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PUT",
    path: "/guilds/{guildId}/reservation-spot-pins/{spotId}",
    operationId: "pinReservationSpot",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/reservation-spot-pins/{spotId}",
    operationId: "unpinReservationSpot",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/reservations",
    operationId: "listMyReservations",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/users/@me/reservations/{reservationId}",
    operationId: "deleteMyReservation",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/users/@me/reservations/{reservationId}",
    operationId: "updateMyReservation",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/reservation-shares",
    operationId: "listReservationShares",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/reservation-share-invitations",
    operationId: "createReservationShareInvitation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/reservation-share-invitations/{invitationId}",
    operationId: "revokeReservationShareInvitation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/reservation-shares/{shareId}",
    operationId: "revokeReservationShare",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/reservation-share-invitations/{token}",
    operationId: "previewReservationShareInvitation",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/reservation-share-invitations/{token}",
    operationId: "acceptReservationShareInvitation",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/notifications/targets",
    operationId: "NotificationsGuildController_getGuildTargets",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/notifications/targets",
    operationId: "NotificationsGuildController_createGuildTarget",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/notifications/targets/available",
    operationId: "NotificationsGuildController_getAvailableGuildTargets",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/notifications/targets/{targetId}",
    operationId: "NotificationsGuildController_deleteGuildTarget",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/notifications/targets/{targetId}",
    operationId: "NotificationsGuildController_updateGuildTarget",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/notifications/rules",
    operationId: "NotificationsGuildController_getGuildRules",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/notifications/rules",
    operationId: "NotificationsGuildController_createGuildRule",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/notifications/rules/{ruleId}",
    operationId: "NotificationsGuildController_deleteGuildRule",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/notifications/rules/{ruleId}",
    operationId: "NotificationsGuildController_updateGuildRule",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/notifications/rules/{ruleId}/rebuild-jobs",
    operationId: "NotificationsGuildController_rebuildGuildRuleJobs",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/notifications/rules/{ruleId}/test",
    operationId: "NotificationsGuildController_triggerGuildRuleTest",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/notifications/jobs",
    operationId: "NotificationsGuildController_getGuildJobs",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/notifications/jobs/{jobId}",
    operationId: "NotificationsGuildController_cancelGuildJob",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/notifications/targets",
    operationId: "NotificationsUserController_getUserTargets",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/notifications/targets",
    operationId: "NotificationsUserController_createUserTarget",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/users/@me/notifications/targets/{targetId}",
    operationId: "NotificationsUserController_deleteUserTarget",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/users/@me/notifications/targets/{targetId}",
    operationId: "NotificationsUserController_updateUserTarget",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/notifications/targets/{targetId}/test",
    operationId: "NotificationsUserController_triggerUserTargetTest",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/notifications/rules",
    operationId: "NotificationsUserController_getUserRules",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/notifications/rules",
    operationId: "NotificationsUserController_createUserRule",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/users/@me/notifications/rules/{ruleId}",
    operationId: "NotificationsUserController_deleteUserRule",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/users/@me/notifications/rules/{ruleId}",
    operationId: "NotificationsUserController_updateUserRule",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/notifications/jobs",
    operationId: "NotificationsUserController_getUserJobs",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/notifications/watched-items",
    operationId: "NotificationsUserController_getWatchedItems",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/notifications/watched-items",
    operationId: "NotificationsUserController_createWatchedItem",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/users/@me/notifications/watched-items/quick-add",
    operationId: "NotificationsUserController_quickAddWatchedItem",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/users/@me/notifications/watched-items/{watchedItemId}",
    operationId: "NotificationsUserController_deleteWatchedItem",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging",
    operationId: "MessagingController_sendNotification",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/{notificationId}/volunteer",
    operationId: "MessagingController_volunteer",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/messaging/party-gathering",
    operationId: "PartyReadyRoomController_list",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/party-gathering",
    operationId: "PartyReadyRoomController_create",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/messaging/party-gathering/{notificationId}",
    operationId: "PartyReadyRoomController_get",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/party-gathering/{notificationId}/applications",
    operationId: "PartyReadyRoomController_apply",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/messaging/party-gathering/{notificationId}/applications/me",
    operationId: "PartyReadyRoomController_withdraw",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/messaging/party-gathering/{notificationId}/participants",
    operationId: "PartyReadyRoomController_remove",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/party-gathering/{notificationId}/invitations/targets",
    operationId: "PartyReadyRoomController_resolveInvitationTargets",
    access: "read",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/party-gathering/{notificationId}/party-observation",
    operationId: "PartyReadyRoomController_observeParty",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "POST",
    path: "/messaging/party-gathering/{notificationId}/cancel",
    operationId: "PartyReadyRoomController_cancel",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/sound-settings",
    operationId: "SoundSettingsController_getSettings",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/sound-settings",
    operationId: "SoundSettingsController_updateSettings",
    access: "write",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events",
    operationId: "listEvents",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events",
    operationId: "createEvent",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}",
    operationId: "showEvent",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}",
    operationId: "deleteEvent",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}",
    operationId: "updateEvent",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/overview",
    operationId: "showEventOverview",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/wrapped",
    operationId: "showEventWrapped",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/maps",
    operationId: "listEventMaps",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/recalculate-points",
    operationId: "recalculateEventPoints",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/assign",
    operationId: "EventsAssignmentController_assignMember",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/assign",
    operationId: "EventsAssignmentController_unassignMember",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/self-assign",
    operationId: "EventsAssignmentController_selfAssignMember",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/self-assign",
    operationId: "EventsAssignmentController_selfUnassignMember",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes",
    operationId: "EventsAssignmentController_addHero",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}",
    operationId: "EventsAssignmentController_deleteHero",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}",
    operationId: "EventsAssignmentController_updateHero",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/maps",
    operationId: "EventsAssignmentController_addMap",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/maps/{mapId}",
    operationId: "EventsAssignmentController_deleteMap",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/locations",
    operationId: "EventsAssignmentController_getLocations",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/locations",
    operationId: "EventsAssignmentController_createLocation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/locations/{locationId}",
    operationId: "EventsAssignmentController_deleteLocation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/locations/{locationId}",
    operationId: "EventsAssignmentController_updateLocation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/locations/reorder",
    operationId: "EventsAssignmentController_reorderLocations",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/maps/{mapId}/location",
    operationId: "EventsAssignmentController_assignMapToLocation",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/participation-confirmations/pending",
    operationId: "listPendingParticipationConfirmations",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/participation-confirmations/expired/acknowledge",
    operationId: "acknowledgeExpiredParticipationConfirmations",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/kills/{killId}/confirm-participation",
    operationId: "confirmParticipationForKill",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/ranking",
    operationId: "listEventRanking",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}/ranking/{rankingId}",
    operationId: "updateRankingPoints",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/timers",
    operationId: "listEventHeroTimers",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/hero-stats",
    operationId: "EventsRankingController_getEventHeroStats",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/kills",
    operationId: "EventsRankingController_getEventKillHistory",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/members/{memberId}/kills",
    operationId: "EventsRankingController_getMemberKillHistory",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/kills",
    operationId: "EventsRankingController_getHeroKillHistory",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/kills/{killId}",
    operationId: "EventsRankingController_getKillDetail",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PATCH",
    path: "/guilds/{guildId}/events/{eventId}/kills/{killId}/points/{killPointId}",
    operationId: "EventsRankingController_updateKillPoint",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/coordination",
    operationId: "EventsMonitoringController_getCoordination",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/kills/{killId}/timeline",
    operationId: "EventsMonitoringController_getKillTimelineData",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/coverage-gaps",
    operationId: "EventsMonitoringController_getHeroCoverageGaps",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/coverage-gaps",
    operationId: "EventsMonitoringController_getMapCoverageGaps",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/maps/{mapId}/active-gap",
    operationId: "EventsMonitoringController_getActiveGapForMap",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/active-gaps",
    operationId: "EventsMonitoringController_getActiveGapsForHero",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/presence-stats",
    operationId: "EventsMonitoringController_getHeroPresenceStats",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/respawn-config",
    operationId: "EventsMonitoringController_getHeroRespawnConfig",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/close-respawn-window",
    operationId: "EventsMonitoringController_closeRespawnWindow",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/events/{eventId}/heroes/{heroId}/open-respawn-window",
    operationId: "EventsMonitoringController_openRespawnWindow",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/pinned-events",
    operationId: "listPinnedEvents",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PUT",
    path: "/guilds/{guildId}/events/{eventId}/pin",
    operationId: "pinEvent",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/events/{eventId}/pin",
    operationId: "unpinEvent",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/maps",
    operationId: "MapsController_getMaps",
    access: "read",
    data: "public",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/map-templates",
    operationId: "MapTemplatesController_getTemplates",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/map-templates",
    operationId: "MapTemplatesController_createTemplate",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "PUT",
    path: "/guilds/{guildId}/map-templates/{templateId}",
    operationId: "MapTemplatesController_updateTemplate",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/map-templates/{templateId}",
    operationId: "MapTemplatesController_deleteTemplate",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/kills",
    operationId: "KillsController_createKill",
    access: "write",
    data: "mixed",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/stats/kills",
    operationId: "KillsController_getGuildKillStats",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/stats/kills",
    operationId: "KillsController_getUserKillStats",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/stats/kills/analytics",
    operationId: "KillsController_getUserKillAnalytics",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/stats/kills/activity",
    operationId: "KillsController_getUserKillActivity",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/users/@me/kills/npcs",
    operationId: "KillsController_getUserNpcKills",
    access: "read",
    data: "personal",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/stats/kills/top-npcs",
    operationId: "KillsController_getGuildTopNpcs",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/stats/kills/top-killers",
    operationId: "KillsController_getGuildTopKillersByType",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/stats/kills/npcs/{npcId}/killers",
    operationId: "KillsController_getNpcKillers",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/stats/kills/members/{memberId}",
    operationId: "KillsController_getMemberKills",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/stats-card/refresh",
    operationId: "AuthenticatedGuildStatsCardController_refreshStatsCard",
    access: "session-only",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/public/guilds/{guildId}/stats-card.png",
    operationId: "PublicGuildStatsCardController_getStatsCard",
    access: "read",
    data: "public",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/docs",
    operationId: "DocsController_getDocuments",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/docs",
    operationId: "DocsController_createDocument",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/docs/trash",
    operationId: "DocsController_getTrash",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/docs/{docId}/history",
    operationId: "DocsController_getHistory",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/docs/{docId}/history/{historyId}",
    operationId: "DocsController_getHistorySnapshot",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "GET",
    path: "/guilds/{guildId}/docs/{docId}",
    operationId: "DocsController_getDocument",
    access: "read",
    data: "organization",
  },
  {
    service: "main",
    method: "PUT",
    path: "/guilds/{guildId}/docs/{docId}",
    operationId: "DocsController_updateDocument",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/docs/{docId}",
    operationId: "DocsController_deleteDocument",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "POST",
    path: "/guilds/{guildId}/docs/{docId}/restore",
    operationId: "DocsController_restoreDocument",
    access: "write",
    data: "organization",
  },
  {
    service: "main",
    method: "DELETE",
    path: "/guilds/{guildId}/docs/{docId}/purge",
    operationId: "DocsController_purgeDocument",
    access: "write",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/healthz",
    operationId: "HealthzController_check",
    access: "session-only",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/activity-logs",
    operationId: "ActivitiesController_findByGuild",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/activity-logs/actor-name-suggestions",
    operationId: "ActivitiesController_suggestActorNames",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/activity-logs/world-suggestions",
    operationId: "ActivitiesController_suggestWorlds",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/activity-logs/clan-name-suggestions",
    operationId: "ActivitiesController_suggestClanNames",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/users/{userId}/activity-logs",
    operationId: "ActivitiesController_findByUser",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/member-activity-stats",
    operationId: "ActivitiesController_getMemberActivityStats",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/guilds/{guildId}/activity-logs/{id}",
    operationId: "ActivitiesController_findOne",
    access: "read",
    data: "organization",
  },
  {
    service: "activity",
    method: "DELETE",
    path: "/guilds/{guildId}/activity-logs/{id}",
    operationId: "ActivitiesController_deleteActivity",
    access: "write",
    data: "organization",
  },
  {
    service: "activity",
    method: "GET",
    path: "/users/@me/activity/online",
    operationId: "UsersActivityController_getOnline",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/healthz",
    operationId: "HealthzController_healthCheck",
    access: "session-only",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "POST",
    path: "/battles",
    operationId: "BattlesController_createBattle",
    access: "write",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me",
    operationId: "BattlesController_getDashboardBattles",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/characters",
    operationId: "BattlesController_getUserCharacters",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/analytics",
    operationId: "BattlesController_getBattleAnalytics",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/abyss/seasons",
    operationId: "BattlesController_getAbyssSeasons",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/combat-profile",
    operationId: "BattlesController_getCombatProfile",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/profession-win-rate",
    operationId: "BattlesController_getProfessionWinRate",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/head-to-head",
    operationId: "BattlesController_getHeadToHead",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/streak",
    operationId: "BattlesController_getCurrentStreak",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/duration",
    operationId: "BattlesController_getBattleDuration",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/ph-growth",
    operationId: "BattlesController_getPhGrowth",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/rating-growth",
    operationId: "BattlesController_getRatingGrowth",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/rating-delta-by-opponent",
    operationId: "BattlesController_getRatingDeltaByOpponent",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/statistics/player-vs-player",
    operationId: "BattlesController_getPlayerVsPlayerBattles",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/warriors/search",
    operationId: "BattlesController_searchWarriors",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/@me/worlds",
    operationId: "BattlesController_getUserWorlds",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/{battleId}/timeline",
    operationId: "BattlesController_getBattleTimeline",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/{battleId}",
    operationId: "BattlesController_getBattle",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "PATCH",
    path: "/battles/{battleId}",
    operationId: "BattlesController_updateBattle",
    access: "write",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "DELETE",
    path: "/battles/{battleId}",
    operationId: "BattlesController_deleteBattle",
    access: "write",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/{battleId}/raw",
    operationId: "BattlesController_getBattleRawData",
    access: "read",
    data: "personal",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/public/{battleId}",
    operationId: "PublicBattlesController_getPublicBattle",
    access: "read",
    data: "public",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/public/{battleId}/raw",
    operationId: "PublicBattlesController_getPublicBattleRaw",
    access: "read",
    data: "public",
  },
  {
    service: "battlelog",
    method: "GET",
    path: "/battles/public/{battleId}/timeline",
    operationId: "PublicBattlesController_getPublicBattleTimeline",
    access: "read",
    data: "public",
  },
  {
    service: "battlelog",
    method: "POST",
    path: "/internal/delete-user-data",
    operationId: "InternalController_deleteUserData",
    access: "session-only",
    data: "personal",
  },
  {
    service: "search",
    method: "GET",
    path: "/healthz",
    operationId: "HealthzController_healthCheck",
    access: "session-only",
    data: "public",
  },
  {
    service: "search",
    method: "GET",
    path: "/players",
    operationId: "PlayersController_getPlayers",
    access: "read",
    data: "public",
  },
  {
    service: "search",
    method: "GET",
    path: "/npcs",
    operationId: "NpcsController_getNpcs",
    access: "read",
    data: "public",
  },
  {
    service: "search",
    method: "GET",
    path: "/items",
    operationId: "ItemsController_getItems",
    access: "read",
    data: "public",
  },
  {
    service: "search",
    method: "GET",
    path: "/all",
    operationId: "AllController_searchAll",
    access: "read",
    data: "public",
  },
] as const satisfies readonly PublicApiOperation[];

export function getPublicApiOperation(
  service: string,
  operationId: string,
): PublicApiOperation | undefined {
  return PUBLIC_API_OPERATIONS.find(
    (operation) =>
      operation.service === service && operation.operationId === operationId,
  );
}
