// Generated by scripts/generate-group-fight-maps.ts from packages/cli mock NPC
// data (margoworld.pl Elite II and Titan pages). Do not edit by hand.
import { normalizeGroupFightName } from "./group-fights.js";
import { getNpcTypeByWt } from "./npc-type.js";
import { NpcTypeEnum } from "@lootlog/schema/npc-type";

export type GroupFightMapNpc = Readonly<{
  name: string;
  npcType: "ELITE2" | "TITAN";
}>;

const catalog: ReadonlyArray<readonly [string, readonly GroupFightMapNpc[]]> = [
  [
    "Arachnitopia p.6",
    [
      { name: "Arachniregina Colosseus", npcType: "ELITE2" },
      { name: "Rycerz z za małym mieczem", npcType: "ELITE2" },
    ],
  ],
  [
    "Bandyckie Chowisko - skarbiec",
    [{ name: "Renegat Baulus", npcType: "TITAN" }],
  ],
  [
    "Cenotaf Berserkerów p.1 - sala 2",
    [{ name: "Berserker Amuno", npcType: "ELITE2" }],
  ],
  [
    "Chantli Cuaitla Citlalina",
    [{ name: "Cuaitl Citlalin", npcType: "ELITE2" }],
  ],
  ["Chata Teściowej", [{ name: "Teściowa Rumcajsa", npcType: "ELITE2" }]],
  ["Chata wójta Fistuły p.1", [{ name: "Wójt Fistuła", npcType: "ELITE2" }]],
  ["Dolina Centaurów", [{ name: "Centaur Zyfryd", npcType: "ELITE2" }]],
  [
    "Drzewo Dusz p.2",
    [
      { name: "Wrzosera", npcType: "ELITE2" },
      { name: "Chryzoprenia", npcType: "ELITE2" },
      { name: "Cantedewia", npcType: "ELITE2" },
    ],
  ],
  ["Drzewo Życia p.3", [{ name: "Nymphemonia", npcType: "ELITE2" }]],
  ["Erem Aldiphrina", [{ name: "Al'diphrin Ilythirahel", npcType: "ELITE2" }]],
  [
    "Erem Czarnego Słońca p.5",
    [{ name: "Grabarz świątynny", npcType: "ELITE2" }],
  ],
  ["Firnowa Grota p.2 s.1", [{ name: "Wielka Stopa", npcType: "ELITE2" }]],
  ["Głębokie Skałki p.3", [{ name: "Tollok Atamatu", npcType: "ELITE2" }]],
  ["Głębokie Skałki p.4", [{ name: "Tollok Utumutu", npcType: "ELITE2" }]],
  ["Gnijące Topielisko", [{ name: "Arytodam olbrzymi", npcType: "ELITE2" }]],
  ["Grobowiec Seta", [{ name: "Neferkar Set", npcType: "ELITE2" }]],
  ["Grota Dzikiego Kota", [{ name: "Mushita", npcType: "ELITE2" }]],
  [
    "Grota Orczej Hordy p.2 s.3",
    [{ name: "Burkog Lorulk", npcType: "ELITE2" }],
  ],
  [
    "Grota Orczych Szamanów p.3 s.1",
    [
      { name: "Sheba Orcza Szamanka", npcType: "ELITE2" },
      { name: "Shakkru", npcType: "ELITE2" },
    ],
  ],
  [
    "Grota Samotnych Dusz p.6",
    [{ name: "Żelazoręki Ohydziarz", npcType: "ELITE2" }],
  ],
  [
    "Jama Morskiej Macki p.1 - sala 3",
    [{ name: "Morski potwór", npcType: "ELITE2" }],
  ],
  ["Jaskinia Caerbannoga", [{ name: "Zabójczy Królik", npcType: "TITAN" }]],
  [
    "Jaskinia Gnollich Szamanów - komnata Kozuga",
    [{ name: "Furruk Kozug", npcType: "ELITE2" }],
  ],
  ["Jaskinia Pogardy", [{ name: "Gobbos", npcType: "ELITE2" }]],
  [
    "Jaszczurze Korytarze p.2 - sala 5",
    [{ name: "Mocny Maddoks", npcType: "ELITE2" }],
  ],
  ["Kamienna Jaskinia - sala 3", [{ name: "Jotun", npcType: "ELITE2" }]],
  [
    "Kamienna Strażnica - Sanktuarium",
    [{ name: "Goplana", npcType: "ELITE2" }],
  ],
  ["Katakumby Gwałtownej Śmierci", [{ name: "Chopesz", npcType: "ELITE2" }]],
  [
    "Komnata Krwawych Obrzędów",
    [{ name: "Przyzywacz Demonów", npcType: "TITAN" }],
  ],
  [
    "Kopalnia Kapiącego Miodu p.2 - sala Owadziej Matki",
    [{ name: "Owadzia Matka", npcType: "ELITE2" }],
  ],
  [
    "Kopalnia Margorii",
    [{ name: "Nadzorczyni krasnoludów", npcType: "ELITE2" }],
  ],
  [
    "Kopalnia Żółtego Kruszcu p.2 - sala 2",
    [{ name: "Grubber Ochlaj", npcType: "ELITE2" }],
  ],
  ["Krypty Bezsennych p.3", [{ name: "Torunia Ankelwald", npcType: "ELITE2" }]],
  [
    "Krypty Dusz Śniegu p.3 - komnata Lisza",
    [{ name: "Lisz", npcType: "ELITE2" }],
  ],
  [
    "Kryształowa Grota - Sala Smutku",
    [{ name: "Królowa Śniegu", npcType: "ELITE2" }],
  ],
  [
    "Krzaczasta Grota - sala główna",
    [{ name: "Silvanasus", npcType: "ELITE2" }],
  ],
  [
    "Kuźnia Worundriela - Komnata Żaru",
    [{ name: "Mistrz Worundriel", npcType: "ELITE2" }],
  ],
  ["Laboratorium Adariel", [{ name: "Adariel", npcType: "ELITE2" }]],
  ["Las Tropicieli", [{ name: "Kotołak Tropiciel", npcType: "ELITE2" }]],
  ["Lazurytowa Grota p.4", [{ name: "Foverk Turrim", npcType: "ELITE2" }]],
  [
    "Lokum Złych Goblinów - pracownia",
    [{ name: "Versus Zoons", npcType: "TITAN" }],
  ],
  [
    "Lokum Złych Goblinów - warsztat",
    [{ name: "Goons Asterus", npcType: "ELITE2" }],
  ],
  [
    "Mała Twierdza - sala główna",
    [{ name: "Fodug Zolash", npcType: "ELITE2" }],
  ],
  ["Margoria - Sala Królewska", [{ name: "Morthen", npcType: "ELITE2" }]],
  ["Migotliwa Pieczara", [{ name: "Dziewicza Orlica", npcType: "TITAN" }]],
  ["Mokra Grota p.2", [{ name: "Agar", npcType: "ELITE2" }]],
  ["Namiot Kambiona", [{ name: "Kambion", npcType: "ELITE2" }]],
  ["Namiot Vari Krugera", [{ name: "Vari Kruger", npcType: "ELITE2" }]],
  [
    "Nawiedzone Kazamaty p.4",
    [{ name: "Duch Władcy Klanów", npcType: "ELITE2" }],
  ],
  [
    "Nora Jaszczurzych Koszmarów - źródło",
    [{ name: "Maddok Magua", npcType: "TITAN" }],
  ],
  ["Ogrza Kawerna p.4", [{ name: "Ogr Stalowy Pazur", npcType: "ELITE2" }]],
  [
    "Ołtarz Pajęczej Bogini",
    [{ name: "Marlloth Malignitas", npcType: "ELITE2" }],
  ],
  [
    "Opuszczony statek - pokład",
    [{ name: "Krab pustelnik", npcType: "ELITE2" }],
  ],
  [
    "Piaskowa Pułapka - Grota Piaskowej Śmierci",
    [{ name: "Stworzyciel", npcType: "ELITE2" }],
  ],
  ["Piaszczysta Grota p.1 - sala 2", [{ name: "Eol", npcType: "ELITE2" }]],
  ["Pieczara Kwiku - sala 2", [{ name: "Tyrtajos", npcType: "ELITE2" }]],
  [
    "Piramida Pustynnego Władcy p.3",
    [{ name: "Ozirus Władca Hieroglifów", npcType: "ELITE2" }],
  ],
  ["Podmokła Dolina", [{ name: "Władca rzek", npcType: "ELITE2" }]],
  [
    "Podziemia Zniszczonej Wieży p.5",
    [{ name: "Jertek Moxos", npcType: "ELITE2" }],
  ],
  [
    "Potępione Zamczysko - pracownia",
    [{ name: "Pogardliwa Sybilla", npcType: "ELITE2" }],
  ],
  [
    "Przeklęta Strażnica - podziemia p.2 s.1",
    [{ name: "Shae Phu", npcType: "ELITE2" }],
  ],
  [
    "Przerażające Sypialnie",
    [{ name: "Sadolia Nadzorczyni Hurys", npcType: "ELITE2" }],
  ],
  [
    "Przysiółek Valmirów",
    [{ name: "Breheret Żelazny Łeb", npcType: "ELITE2" }],
  ],
  [
    "Sala Królewska",
    [{ name: "Lusgrathera Królowa Pramatka", npcType: "ELITE2" }],
  ],
  ["Sala Lodowej Magii", [{ name: "Artenius", npcType: "ELITE2" }]],
  ["Sala Mroźnych Strzał", [{ name: "Furion", npcType: "ELITE2" }]],
  ["Sala Mroźnych Szeptów", [{ name: "Zorin", npcType: "ELITE2" }]],
  [
    "Sala Rady Orków",
    [
      { name: "Bragarth Myśliwy Dusz", npcType: "ELITE2" },
      { name: "Fursharag Pożeracz Umysłów", npcType: "ELITE2" },
      { name: "Ziuggrael Strażnik Królowej", npcType: "ELITE2" },
    ],
  ],
  [
    "Sala Skaryfikacji Grzeszników",
    [{ name: "Sataniel Skrytobójca", npcType: "ELITE2" }],
  ],
  ["Sala Tronowa", [{ name: "Tanroth", npcType: "TITAN" }]],
  ["Sala Tysiąca Świec", [{ name: "Zufulus Smakosz Serc", npcType: "ELITE2" }]],
  [
    "Sala Zrujnowanej Świątyni",
    [{ name: "Barbatos Smoczy Strażnik", npcType: "TITAN" }],
  ],
  [
    "Sale Rozdzierania",
    [{ name: "Bergermona Krwawa Hrabina", npcType: "ELITE2" }],
  ],
  ["Schowek na Łupy", [{ name: "Zorg Jednooki Baron", npcType: "ELITE2" }]],
  ["Skalne Cmentarzysko p.4", [{ name: "Łowca czaszek", npcType: "ELITE2" }]],
  ["Skalne Turnie", [{ name: "Tollok Shimger", npcType: "ELITE2" }]],
  ["Skarpa Trzech Słów", [{ name: "Pięknotka Mięsożerna", npcType: "ELITE2" }]],
  ["Stare Wyrobisko p.3", [{ name: "Razuglag Oklash", npcType: "ELITE2" }]],
  ["Starodrzew Przedwiecznych p.2", [{ name: "Cerasus", npcType: "ELITE2" }]],
  [
    "Stary Kupiecki Trakt",
    [{ name: "Szczęt alias Gładki", npcType: "ELITE2" }],
  ],
  [
    "Szlamowe Kanały p.2 - sala 3",
    [{ name: "Mysiur Myświórowy Król", npcType: "ELITE2" }],
  ],
  [
    "Świątynia Andarum - zbrojownia",
    [{ name: "Podły zbrojmistrz", npcType: "ELITE2" }],
  ],
  [
    "Świątynia Hebrehotha - sala czciciela",
    [{ name: "Chaegd Agnrakh", npcType: "ELITE2" }],
  ],
  [
    "Świątynia Hebrehotha - sala ofiary",
    [{ name: "Vaenra Charkhaam", npcType: "ELITE2" }],
  ],
  [
    "Tajemnicza Siedziba",
    [
      { name: "Annaniel Wysysacz Marzeń", npcType: "ELITE2" },
      { name: "Gothardus Kolekcjoner Głów", npcType: "ELITE2" },
    ],
  ],
  ["Teotihuacan", [{ name: "Tezcatlipoca", npcType: "TITAN" }]],
  [
    "Twierdza Rogogłowych - Sala Byka",
    [{ name: "Borgoros Garamir III", npcType: "ELITE2" }],
  ],
  [
    "Ukryta Grota Morskich Diabłów - magazyn",
    [{ name: "Młody Jack Truciciel", npcType: "ELITE2" }],
  ],
  [
    "Ukryta Grota Morskich Diabłów - siedziba",
    [{ name: "Helga Opiekunka Rumu", npcType: "ELITE2" }],
  ],
  [
    "Ukryta Grota Morskich Diabłów - skarbiec",
    [{ name: "Henry Kaprawe Oko", npcType: "ELITE2" }],
  ],
  ["Urwisko Vapora", [{ name: "Terrozaur", npcType: "ELITE2" }]],
  ["Wschodni Mictlan p.9", [{ name: "Quetzalcoatl", npcType: "ELITE2" }]],
  [
    "Wulkan Politraki - Piekielne Czeluście",
    [{ name: "Piekielny Arcymag", npcType: "TITAN" }],
  ],
  ["Wulkan Politraki p.1 - sala 3", [{ name: "Ifryt", npcType: "ELITE2" }]],
  ["Wylęgarnia Choukkerów p.1", [{ name: "Choukker", npcType: "ELITE2" }]],
  [
    "Zabłocona Jama p.2 - Sala Błotnistych Odmętów",
    [{ name: "Miłośnik rycerzy", npcType: "ELITE2" }],
  ],
  [
    "Zabłocona Jama p.2 - Sala Duszącej Stęchlizny",
    [{ name: "Miłośnik łowców", npcType: "ELITE2" }],
  ],
  [
    "Zabłocona Jama p.2 - Sala Magicznego Błota",
    [{ name: "Miłośnik magii", npcType: "ELITE2" }],
  ],
  ["Zachodni Mictlan p.9", [{ name: "Yaotl", npcType: "ELITE2" }]],
  ["Zagrzybiałe Ścieżki p.3", [{ name: "Gnom Figlid", npcType: "ELITE2" }]],
  ["Zalana Grota", [{ name: "Czempion Furboli", npcType: "ELITE2" }]],
  ["Zapomniany Święty Gaj p.3", [{ name: "Leśne Widmo", npcType: "ELITE2" }]],
  ["Złota Góra p.2 s.1", [{ name: "Tolypeutes", npcType: "ELITE2" }]],
  ["Źródło Wspomnień", [{ name: "Łowczyni Wspomnień", npcType: "TITAN" }]],
  ["Źródło Zakorzenionego Ludu", [{ name: "Dendroculus", npcType: "ELITE2" }]],
];

/** In-game map names that host at least one Elite II or Titan NPC. */
export const GROUP_FIGHT_MAP_NAMES: ReadonlyArray<string> = catalog.map(
  ([name]) => name,
);

const normalizedGroupFightMapNpcs = new Map(
  catalog.map(([name, npcs]) => [normalizeGroupFightName(name), npcs]),
);

export const getGroupFightMapNpcs = (
  mapName: string | null | undefined,
): readonly GroupFightMapNpc[] =>
  typeof mapName === "string"
    ? (normalizedGroupFightMapNpcs.get(normalizeGroupFightName(mapName)) ?? [])
    : [];

export const isGroupFightMap = (mapName: string | null | undefined): boolean =>
  getGroupFightMapNpcs(mapName).length > 0;

export const getGroupFightNpcType = (
  weight: number | undefined,
): GroupFightMapNpc["npcType"] | null => {
  if (weight === undefined || !Number.isFinite(weight)) return null;
  const npcType = getNpcTypeByWt(NpcTypeEnum, weight);
  return npcType === NpcTypeEnum.ELITE2 || npcType === NpcTypeEnum.TITAN
    ? npcType
    : null;
};

export const isGroupFightNpcWeight = (weight: number | undefined): boolean =>
  getGroupFightNpcType(weight) !== null;

/** Qualifies a red map using the catalog or an NPC observed in this map epoch. */
export const isQualifyingGroupFightMap = (input: {
  readonly name: string | null | undefined;
  readonly pvp: number | null | undefined;
  readonly observedNpcWeight?: number;
}): boolean => {
  if (input.pvp !== 2) return false;
  if (isGroupFightMap(input.name)) return true;
  return isGroupFightNpcWeight(input.observedNpcWeight);
};
