// Generated by scripts/generate-group-fight-maps.ts from packages/cli mock NPC
// data (margoworld.pl Elite II and Titan pages). Do not edit by hand.
import { normalizeGroupFightName } from "./group-fights.js";
import { getNpcTypeByWt } from "./npc-type.js";
import { NpcTypeEnum } from "@lootlog/schema/npc-type";

export type GroupFightMapNpc = Readonly<{
  name: string;
  npcType: "ELITE2" | "TITAN";
  lvl: number;
  icon: string;
}>;

const catalog: ReadonlyArray<readonly [string, readonly GroupFightMapNpc[]]> = [
  [
    "Arachnitopia p.6",
    [
      {
        name: "Arachniregina Colosseus",
        npcType: "ELITE2",
        lvl: 214,
        icon: "e2/regina-e2.gif",
      },
      {
        name: "Rycerz z za małym mieczem",
        npcType: "ELITE2",
        lvl: 214,
        icon: "e2/pajeczy16.gif",
      },
    ],
  ],
  [
    "Bandyckie Chowisko - skarbiec",
    [
      {
        name: "Renegat Baulus",
        npcType: "TITAN",
        lvl: 101,
        icon: "tyt/renegat_baulus.gif",
      },
    ],
  ],
  [
    "Cenotaf Berserkerów p.1 - sala 2",
    [
      {
        name: "Berserker Amuno",
        npcType: "ELITE2",
        lvl: 148,
        icon: "e2/amuno.gif",
      },
    ],
  ],
  [
    "Chantli Cuaitla Citlalina",
    [
      {
        name: "Cuaitl Citlalin",
        npcType: "ELITE2",
        lvl: 250,
        icon: "e2/maho-cuaitl.gif",
      },
    ],
  ],
  [
    "Chata Teściowej",
    [
      {
        name: "Teściowa Rumcajsa",
        npcType: "ELITE2",
        lvl: 145,
        icon: "e2/goral-e2-tesciowa-rumcajsa.gif",
      },
    ],
  ],
  [
    "Chata wójta Fistuły p.1",
    [
      {
        name: "Wójt Fistuła",
        npcType: "ELITE2",
        lvl: 144,
        icon: "e2/goral-e2-wojt-fistula.gif",
      },
    ],
  ],
  [
    "Dolina Centaurów",
    [
      {
        name: "Centaur Zyfryd",
        npcType: "ELITE2",
        lvl: 99,
        icon: "e2/cent-zyfryd.gif",
      },
    ],
  ],
  [
    "Drzewo Dusz p.2",
    [
      {
        name: "Wrzosera",
        npcType: "ELITE2",
        lvl: 177,
        icon: "e2/wrzosera-1b.gif",
      },
      {
        name: "Chryzoprenia",
        npcType: "ELITE2",
        lvl: 177,
        icon: "e2/chryzoprenia-1a.gif",
      },
      {
        name: "Cantedewia",
        npcType: "ELITE2",
        lvl: 177,
        icon: "e2/cantedewia-1a.gif",
      },
    ],
  ],
  [
    "Drzewo Życia p.3",
    [
      {
        name: "Nymphemonia",
        npcType: "ELITE2",
        lvl: 287,
        icon: "e2/nymphemonia.gif",
      },
    ],
  ],
  [
    "Erem Aldiphrina",
    [
      {
        name: "Al'diphrin Ilythirahel",
        npcType: "ELITE2",
        lvl: 218,
        icon: "e2/drow-aldiphrin-wladca.gif",
      },
    ],
  ],
  [
    "Erem Czarnego Słońca p.5",
    [
      {
        name: "Grabarz świątynny",
        npcType: "ELITE2",
        lvl: 80,
        icon: "e2/nieu_mnich_grabarz.gif",
      },
    ],
  ],
  [
    "Firnowa Grota p.2 s.1",
    [
      {
        name: "Wielka Stopa",
        npcType: "ELITE2",
        lvl: 82,
        icon: "e2/wlochacze_wielka_stopa.gif",
      },
    ],
  ],
  [
    "Głębokie Skałki p.3",
    [
      {
        name: "Tollok Atamatu",
        npcType: "ELITE2",
        lvl: 73,
        icon: "e2/tollok_jask_atamatu.gif",
      },
    ],
  ],
  [
    "Głębokie Skałki p.4",
    [
      {
        name: "Tollok Utumutu",
        npcType: "ELITE2",
        lvl: 73,
        icon: "e2/tollok_jask_utumatu.gif",
      },
    ],
  ],
  [
    "Gnijące Topielisko",
    [
      {
        name: "Arytodam olbrzymi",
        npcType: "ELITE2",
        lvl: 226,
        icon: "e2/arytodam_olbrzymi-1b.gif",
      },
    ],
  ],
  [
    "Grobowiec Seta",
    [
      {
        name: "Neferkar Set",
        npcType: "ELITE2",
        lvl: 274,
        icon: "e2/szkiel_set.gif",
      },
    ],
  ],
  [
    "Grota Dzikiego Kota",
    [{ name: "Mushita", npcType: "ELITE2", lvl: 23, icon: "e2/st-puma.gif" }],
  ],
  [
    "Grota Orczej Hordy p.2 s.3",
    [
      {
        name: "Burkog Lorulk",
        npcType: "ELITE2",
        lvl: 160,
        icon: "e2/orkczd.gif",
      },
    ],
  ],
  [
    "Grota Orczych Szamanów p.3 s.1",
    [
      {
        name: "Sheba Orcza Szamanka",
        npcType: "ELITE2",
        lvl: 160,
        icon: "e2/r_orc_sheba.gif",
      },
      {
        name: "Shakkru",
        npcType: "ELITE2",
        lvl: 160,
        icon: "e2/r_orc_shakkru.gif",
      },
    ],
  ],
  [
    "Grota Samotnych Dusz p.6",
    [
      {
        name: "Żelazoręki Ohydziarz",
        npcType: "ELITE2",
        lvl: 92,
        icon: "e2/ugrape2.gif",
      },
    ],
  ],
  [
    "Jama Morskiej Macki p.1 - sala 3",
    [
      {
        name: "Morski potwór",
        npcType: "ELITE2",
        lvl: 118,
        icon: "e2/osmiornica-1b.gif",
      },
    ],
  ],
  [
    "Jaskinia Caerbannoga",
    [
      {
        name: "Zabójczy Królik",
        npcType: "TITAN",
        lvl: 70,
        icon: "tyt/zabojczy_krolik.gif",
      },
    ],
  ],
  [
    "Jaskinia Gnollich Szamanów - komnata Kozuga",
    [
      {
        name: "Furruk Kozug",
        npcType: "ELITE2",
        lvl: 66,
        icon: "e2/gnoll12.gif",
      },
    ],
  ],
  [
    "Jaskinia Pogardy",
    [{ name: "Gobbos", npcType: "ELITE2", lvl: 40, icon: "e2/gobsamurai.gif" }],
  ],
  [
    "Jaszczurze Korytarze p.2 - sala 5",
    [
      {
        name: "Mocny Maddoks",
        npcType: "ELITE2",
        lvl: 231,
        icon: "e2/mocny_maddoks-1b.gif",
      },
    ],
  ],
  [
    "Kamienna Jaskinia - sala 3",
    [
      {
        name: "Jotun",
        npcType: "ELITE2",
        lvl: 70,
        icon: "e2/kam_olbrzym-b.gif",
      },
    ],
  ],
  [
    "Kamienna Strażnica - Sanktuarium",
    [{ name: "Goplana", npcType: "ELITE2", lvl: 93, icon: "e2/goplana.gif" }],
  ],
  [
    "Katakumby Gwałtownej Śmierci",
    [{ name: "Chopesz", npcType: "ELITE2", lvl: 267, icon: "e2/chopesh2.gif" }],
  ],
  [
    "Komnata Krwawych Obrzędów",
    [
      {
        name: "Przyzywacz Demonów",
        npcType: "TITAN",
        lvl: 204,
        icon: "tyt/przyz_demon_sekta.gif",
      },
    ],
  ],
  [
    "Kopalnia Kapiącego Miodu p.2 - sala Owadziej Matki",
    [
      {
        name: "Owadzia Matka",
        npcType: "ELITE2",
        lvl: 58,
        icon: "e2/zadlak-e2-owadzia-matka.gif",
      },
    ],
  ],
  [
    "Kopalnia Margorii",
    [
      {
        name: "Nadzorczyni krasnoludów",
        npcType: "ELITE2",
        lvl: 88,
        icon: "e2/nadzorczyni_krasnoludow.gif",
      },
    ],
  ],
  [
    "Kopalnia Żółtego Kruszcu p.2 - sala 2",
    [
      {
        name: "Grubber Ochlaj",
        npcType: "ELITE2",
        lvl: 136,
        icon: "e2/grubber-ochlaj.gif",
      },
    ],
  ],
  [
    "Krypty Bezsennych p.3",
    [
      {
        name: "Torunia Ankelwald",
        npcType: "ELITE2",
        lvl: 186,
        icon: "e2/thuz-patr1.gif",
      },
    ],
  ],
  [
    "Krypty Dusz Śniegu p.3 - komnata Lisza",
    [
      {
        name: "Lisz",
        npcType: "ELITE2",
        lvl: 75,
        icon: "e2/lisz_demilisze.gif",
      },
    ],
  ],
  [
    "Kryształowa Grota - Sala Smutku",
    [
      {
        name: "Królowa Śniegu",
        npcType: "ELITE2",
        lvl: 175,
        icon: "e2/krolowa-sniegu.gif",
      },
    ],
  ],
  [
    "Krzaczasta Grota - sala główna",
    [
      {
        name: "Silvanasus",
        npcType: "ELITE2",
        lvl: 235,
        icon: "e2/silvanasus.gif",
      },
    ],
  ],
  [
    "Kuźnia Worundriela - Komnata Żaru",
    [
      {
        name: "Mistrz Worundriel",
        npcType: "ELITE2",
        lvl: 139,
        icon: "e2/worundriel02.gif",
      },
    ],
  ],
  [
    "Laboratorium Adariel",
    [
      {
        name: "Adariel",
        npcType: "ELITE2",
        lvl: 155,
        icon: "e2/tri_adariel.gif",
      },
    ],
  ],
  [
    "Las Tropicieli",
    [
      {
        name: "Kotołak Tropiciel",
        npcType: "ELITE2",
        lvl: 27,
        icon: "e1/kotolak_lowca.gif",
      },
    ],
  ],
  [
    "Lazurytowa Grota p.4",
    [
      {
        name: "Foverk Turrim",
        npcType: "ELITE2",
        lvl: 57,
        icon: "e2/kobold07.gif",
      },
    ],
  ],
  [
    "Lokum Złych Goblinów - pracownia",
    [
      {
        name: "Versus Zoons",
        npcType: "TITAN",
        lvl: 154,
        icon: "tyt/versus-zoons.gif",
      },
    ],
  ],
  [
    "Lokum Złych Goblinów - warsztat",
    [
      {
        name: "Goons Asterus",
        npcType: "ELITE2",
        lvl: 154,
        icon: "e2/goons_asterus-1a.gif",
      },
    ],
  ],
  [
    "Mała Twierdza - sala główna",
    [
      {
        name: "Fodug Zolash",
        npcType: "ELITE2",
        lvl: 150,
        icon: "e2/fodug_zolash.gif",
      },
    ],
  ],
  [
    "Margoria - Sala Królewska",
    [
      {
        name: "Morthen",
        npcType: "ELITE2",
        lvl: 89,
        icon: "e2/krasnolud_boss.gif",
      },
    ],
  ],
  [
    "Migotliwa Pieczara",
    [
      {
        name: "Dziewicza Orlica",
        npcType: "TITAN",
        lvl: 51,
        icon: "tyt/dziewicza_orlica.gif",
      },
    ],
  ],
  [
    "Mokra Grota p.2",
    [{ name: "Agar", npcType: "ELITE2", lvl: 51, icon: "e2/glut_agar.gif" }],
  ],
  [
    "Namiot Kambiona",
    [{ name: "Kambion", npcType: "ELITE2", lvl: 101, icon: "e2/kambion.gif" }],
  ],
  [
    "Namiot Vari Krugera",
    [
      {
        name: "Vari Kruger",
        npcType: "ELITE2",
        lvl: 65,
        icon: "e2/gnoll11.gif",
      },
    ],
  ],
  [
    "Nawiedzone Kazamaty p.4",
    [
      {
        name: "Duch Władcy Klanów",
        npcType: "ELITE2",
        lvl: 165,
        icon: "e2/duch_wladcy_kl.gif",
      },
    ],
  ],
  [
    "Nora Jaszczurzych Koszmarów - źródło",
    [
      {
        name: "Maddok Magua",
        npcType: "TITAN",
        lvl: 231,
        icon: "tyt/maddok_magua-1b.gif",
      },
    ],
  ],
  [
    "Ogrza Kawerna p.4",
    [
      {
        name: "Ogr Stalowy Pazur",
        npcType: "ELITE2",
        lvl: 183,
        icon: "e2/ogr_stalowy_pazur-1a.gif",
      },
    ],
  ],
  [
    "Ołtarz Pajęczej Bogini",
    [
      {
        name: "Marlloth Malignitas",
        npcType: "ELITE2",
        lvl: 220,
        icon: "e2/drider-marlloth.gif",
      },
    ],
  ],
  [
    "Opuszczony statek - pokład",
    [
      {
        name: "Krab pustelnik",
        npcType: "ELITE2",
        lvl: 124,
        icon: "e2/krab_big3.gif",
      },
    ],
  ],
  [
    "Piaskowa Pułapka - Grota Piaskowej Śmierci",
    [
      {
        name: "Stworzyciel",
        npcType: "ELITE2",
        lvl: 125,
        icon: "e2/stworzyciel.gif",
      },
    ],
  ],
  [
    "Piaszczysta Grota p.1 - sala 2",
    [
      {
        name: "Eol",
        npcType: "ELITE2",
        lvl: 135,
        icon: "e2/piaskowy_potwor-6a.gif",
      },
    ],
  ],
  [
    "Pieczara Kwiku - sala 2",
    [{ name: "Tyrtajos", npcType: "ELITE2", lvl: 42, icon: "e2/dzik.gif" }],
  ],
  [
    "Piramida Pustynnego Władcy p.3",
    [
      {
        name: "Ozirus Władca Hieroglifów",
        npcType: "ELITE2",
        lvl: 115,
        icon: "e2/mumia-ozirus.gif",
      },
    ],
  ],
  [
    "Podmokła Dolina",
    [
      {
        name: "Władca rzek",
        npcType: "ELITE2",
        lvl: 37,
        icon: "e2/gobmag2.gif",
      },
    ],
  ],
  [
    "Podziemia Zniszczonej Wieży p.5",
    [
      {
        name: "Jertek Moxos",
        npcType: "ELITE2",
        lvl: 105,
        icon: "e2/moloch-jertek.gif",
      },
    ],
  ],
  [
    "Potępione Zamczysko - pracownia",
    [
      {
        name: "Pogardliwa Sybilla",
        npcType: "ELITE2",
        lvl: 255,
        icon: "e2/tri2_witch_e2.gif",
      },
    ],
  ],
  [
    "Przeklęta Strażnica - podziemia p.2 s.1",
    [
      {
        name: "Shae Phu",
        npcType: "ELITE2",
        lvl: 30,
        icon: "e2/demonszef.gif",
      },
    ],
  ],
  [
    "Przerażające Sypialnie",
    [
      {
        name: "Sadolia Nadzorczyni Hurys",
        npcType: "ELITE2",
        lvl: 200,
        icon: "e2/sekta-sadolia.gif",
      },
    ],
  ],
  [
    "Przysiółek Valmirów",
    [
      {
        name: "Breheret Żelazny Łeb",
        npcType: "ELITE2",
        lvl: 192,
        icon: "e2/draki-breheret-1b.gif",
      },
    ],
  ],
  [
    "Sala Królewska",
    [
      {
        name: "Lusgrathera Królowa Pramatka",
        npcType: "ELITE2",
        lvl: 175,
        icon: "e2/prakrolowa.gif",
      },
    ],
  ],
  [
    "Sala Lodowej Magii",
    [
      {
        name: "Artenius",
        npcType: "ELITE2",
        lvl: 300,
        icon: "e2/wl-mrozu03.gif",
      },
    ],
  ],
  [
    "Sala Mroźnych Strzał",
    [
      {
        name: "Furion",
        npcType: "ELITE2",
        lvl: 300,
        icon: "e2/wl-mrozu02.gif",
      },
    ],
  ],
  [
    "Sala Mroźnych Szeptów",
    [{ name: "Zorin", npcType: "ELITE2", lvl: 300, icon: "e2/wl-mrozu01.gif" }],
  ],
  [
    "Sala Rady Orków",
    [
      {
        name: "Bragarth Myśliwy Dusz",
        npcType: "ELITE2",
        lvl: 170,
        icon: "e2/praork_low_elita.gif",
      },
      {
        name: "Fursharag Pożeracz Umysłów",
        npcType: "ELITE2",
        lvl: 170,
        icon: "e2/praork_mag_elita.gif",
      },
      {
        name: "Ziuggrael Strażnik Królowej",
        npcType: "ELITE2",
        lvl: 170,
        icon: "e2/praork_woj_elita.gif",
      },
    ],
  ],
  [
    "Sala Skaryfikacji Grzeszników",
    [
      {
        name: "Sataniel Skrytobójca",
        npcType: "ELITE2",
        lvl: 204,
        icon: "e2/sekta-sataniel.gif",
      },
    ],
  ],
  [
    "Sala Tronowa",
    [{ name: "Tanroth", npcType: "TITAN", lvl: 300, icon: "tyt/ice_king.gif" }],
  ],
  [
    "Sala Tysiąca Świec",
    [
      {
        name: "Zufulus Smakosz Serc",
        npcType: "ELITE2",
        lvl: 205,
        icon: "e2/sekta-zufulus.gif",
      },
    ],
  ],
  [
    "Sala Zrujnowanej Świątyni",
    [
      {
        name: "Barbatos Smoczy Strażnik",
        npcType: "TITAN",
        lvl: 285,
        icon: "tyt/hebrehoth_smokoludzie.gif",
      },
    ],
  ],
  [
    "Sale Rozdzierania",
    [
      {
        name: "Bergermona Krwawa Hrabina",
        npcType: "ELITE2",
        lvl: 204,
        icon: "e2/sekta-bergermona.gif",
      },
    ],
  ],
  [
    "Schowek na Łupy",
    [
      {
        name: "Zorg Jednooki Baron",
        npcType: "ELITE2",
        lvl: 33,
        icon: "e2/zbir-e2-zorg.gif",
      },
    ],
  ],
  [
    "Skalne Cmentarzysko p.4",
    [
      {
        name: "Łowca czaszek",
        npcType: "ELITE2",
        lvl: 112,
        icon: "e2/alghul-czaszka-1a.gif",
      },
    ],
  ],
  [
    "Skalne Turnie",
    [
      {
        name: "Tollok Shimger",
        npcType: "ELITE2",
        lvl: 47,
        icon: "e2/tollok_shimger.gif",
      },
    ],
  ],
  [
    "Skarpa Trzech Słów",
    [
      {
        name: "Pięknotka Mięsożerna",
        npcType: "ELITE2",
        lvl: 189,
        icon: "e2/zmutowana-roslinka.gif",
      },
    ],
  ],
  [
    "Stare Wyrobisko p.3",
    [
      {
        name: "Razuglag Oklash",
        npcType: "ELITE2",
        lvl: 51,
        icon: "e2/razuglag.gif",
      },
    ],
  ],
  [
    "Starodrzew Przedwiecznych p.2",
    [
      {
        name: "Cerasus",
        npcType: "ELITE2",
        lvl: 193,
        icon: "e2/cerasus-1a.gif",
      },
    ],
  ],
  [
    "Stary Kupiecki Trakt",
    [
      {
        name: "Szczęt alias Gładki",
        npcType: "ELITE2",
        lvl: 47,
        icon: "e2/zbir-szczet.gif",
      },
    ],
  ],
  [
    "Szlamowe Kanały p.2 - sala 3",
    [
      {
        name: "Mysiur Myświórowy Król",
        npcType: "ELITE2",
        lvl: 197,
        icon: "e2/mysiur_myswiorowy_krol-1a.gif",
      },
    ],
  ],
  [
    "Świątynia Andarum - zbrojownia",
    [
      {
        name: "Podły zbrojmistrz",
        npcType: "ELITE2",
        lvl: 82,
        icon: "e2/magaz_zbrojmistrz.gif",
      },
    ],
  ],
  [
    "Świątynia Hebrehotha - sala czciciela",
    [
      {
        name: "Chaegd Agnrakh",
        npcType: "ELITE2",
        lvl: 280,
        icon: "e2/bar_smokoszef.gif",
      },
    ],
  ],
  [
    "Świątynia Hebrehotha - sala ofiary",
    [
      {
        name: "Vaenra Charkhaam",
        npcType: "ELITE2",
        lvl: 280,
        icon: "e2/bar_smoczyca.gif",
      },
    ],
  ],
  [
    "Tajemnicza Siedziba",
    [
      {
        name: "Annaniel Wysysacz Marzeń",
        npcType: "ELITE2",
        lvl: 204,
        icon: "e2/sekta-annaniel.gif",
      },
      {
        name: "Gothardus Kolekcjoner Głów",
        npcType: "ELITE2",
        lvl: 204,
        icon: "e2/sekta-gothardus.gif",
      },
    ],
  ],
  [
    "Teotihuacan",
    [
      {
        name: "Tezcatlipoca",
        npcType: "TITAN",
        lvl: 258,
        icon: "tyt/tezcatlipoca.gif",
      },
    ],
  ],
  [
    "Twierdza Rogogłowych - Sala Byka",
    [
      {
        name: "Borgoros Garamir III",
        npcType: "ELITE2",
        lvl: 124,
        icon: "e2/ingotia_minotaur-7a.gif",
      },
    ],
  ],
  [
    "Ukryta Grota Morskich Diabłów - magazyn",
    [
      {
        name: "Młody Jack Truciciel",
        npcType: "ELITE2",
        lvl: 131,
        icon: "e2/pirat01.gif",
      },
    ],
  ],
  [
    "Ukryta Grota Morskich Diabłów - siedziba",
    [
      {
        name: "Helga Opiekunka Rumu",
        npcType: "ELITE2",
        lvl: 131,
        icon: "e2/pirat-2b.gif",
      },
    ],
  ],
  [
    "Ukryta Grota Morskich Diabłów - skarbiec",
    [
      {
        name: "Henry Kaprawe Oko",
        npcType: "ELITE2",
        lvl: 131,
        icon: "e1/pirat5b.gif",
      },
    ],
  ],
  [
    "Urwisko Vapora",
    [
      {
        name: "Terrozaur",
        npcType: "ELITE2",
        lvl: 280,
        icon: "e2/terrorzaur_pus.gif",
      },
    ],
  ],
  [
    "Wschodni Mictlan p.9",
    [
      {
        name: "Quetzalcoatl",
        npcType: "ELITE2",
        lvl: 260,
        icon: "e2/quetzalcoatl.gif",
      },
    ],
  ],
  [
    "Wulkan Politraki - Piekielne Czeluście",
    [
      {
        name: "Piekielny Arcymag",
        npcType: "TITAN",
        lvl: 131,
        icon: "tyt/archdemon.gif",
      },
    ],
  ],
  [
    "Wulkan Politraki p.1 - sala 3",
    [
      {
        name: "Ifryt",
        npcType: "ELITE2",
        lvl: 128,
        icon: "e2/magradit_ifryt.gif",
      },
    ],
  ],
  [
    "Wylęgarnia Choukkerów p.1",
    [
      {
        name: "Choukker",
        npcType: "ELITE2",
        lvl: 84,
        icon: "e2/dlawiciel5.gif",
      },
    ],
  ],
  [
    "Zabłocona Jama p.2 - Sala Błotnistych Odmętów",
    [
      {
        name: "Miłośnik rycerzy",
        npcType: "ELITE2",
        lvl: 108,
        icon: "e2/blotniaki_milosnik_rycerzy.gif",
      },
    ],
  ],
  [
    "Zabłocona Jama p.2 - Sala Duszącej Stęchlizny",
    [
      {
        name: "Miłośnik łowców",
        npcType: "ELITE2",
        lvl: 108,
        icon: "e2/blotniaki_milosnik_lowcow.gif",
      },
    ],
  ],
  [
    "Zabłocona Jama p.2 - Sala Magicznego Błota",
    [
      {
        name: "Miłośnik magii",
        npcType: "ELITE2",
        lvl: 108,
        icon: "e2/blotniaki_milosnik_magii.gif",
      },
    ],
  ],
  [
    "Zachodni Mictlan p.9",
    [{ name: "Yaotl", npcType: "ELITE2", lvl: 258, icon: "e2/mahoplowca.gif" }],
  ],
  [
    "Zagrzybiałe Ścieżki p.3",
    [
      {
        name: "Gnom Figlid",
        npcType: "ELITE2",
        lvl: 96,
        icon: "e2/gnom_figlid.gif",
      },
    ],
  ],
  [
    "Zalana Grota",
    [
      {
        name: "Czempion Furboli",
        npcType: "ELITE2",
        lvl: 210,
        icon: "e2/forbol03.gif",
      },
    ],
  ],
  [
    "Zapomniany Święty Gaj p.3",
    [
      {
        name: "Leśne Widmo",
        npcType: "ELITE2",
        lvl: 92,
        icon: "e2/lesne_widmo.gif",
      },
    ],
  ],
  [
    "Złota Góra p.2 s.1",
    [
      {
        name: "Tolypeutes",
        npcType: "ELITE2",
        lvl: 245,
        icon: "e2/bolita.gif",
      },
    ],
  ],
  [
    "Źródło Wspomnień",
    [
      {
        name: "Łowczyni Wspomnień",
        npcType: "TITAN",
        lvl: 177,
        icon: "tyt/lowcz-wspo-driady.gif",
      },
    ],
  ],
  [
    "Źródło Zakorzenionego Ludu",
    [
      {
        name: "Dendroculus",
        npcType: "ELITE2",
        lvl: 240,
        icon: "e2/dendroculus.gif",
      },
    ],
  ],
];

/** In-game map names that host at least one Elite II or Titan NPC. */
export const GROUP_FIGHT_MAP_NAMES: ReadonlyArray<string> = catalog.map(
  ([name]) => name,
);

const normalizedGroupFightMapNpcs = new Map(
  catalog.map(([name, npcs]) => [normalizeGroupFightName(name), npcs]),
);

export const getGroupFightMapNpcs = (
  mapName: string | null | undefined,
): readonly GroupFightMapNpc[] =>
  mapName === null || mapName === undefined
    ? []
    : (normalizedGroupFightMapNpcs.get(normalizeGroupFightName(mapName)) ?? []);

export const isGroupFightMap = (mapName: string | null | undefined): boolean =>
  getGroupFightMapNpcs(mapName).length > 0;

export const getGroupFightNpcType = (
  weight: number | undefined,
): GroupFightMapNpc["npcType"] | null => {
  if (weight === undefined || !Number.isFinite(weight)) return null;
  const npcType = getNpcTypeByWt(NpcTypeEnum, weight);
  return npcType === NpcTypeEnum.ELITE2 || npcType === NpcTypeEnum.TITAN
    ? npcType
    : null;
};

export const isGroupFightNpcWeight = (weight: number | undefined): boolean =>
  getGroupFightNpcType(weight) !== null;

/** Qualifies a red map using the catalog or an NPC observed in this map epoch. */
export const isQualifyingGroupFightMap = (input: {
  readonly name: string | null | undefined;
  readonly pvp: number | null | undefined;
  readonly observedNpcWeight?: number;
}): boolean => {
  if (input.pvp !== 2) return false;
  if (isGroupFightMap(input.name)) return true;
  return isGroupFightNpcWeight(input.observedNpcWeight);
};
