namespace: lootlog-prod
resources:
  - ../../base/activity
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-activity
    newTag: prod-5412887bc1c64bc1a9301107536728fcac11c2fa
namePrefix: prod-
