namespace: lootlog-prod
resources:
  - ../../base/activity
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-activity
    newTag: prod-dae0b24e72f95f97e51cdeb987b645b8b56fd966
namePrefix: prod-
