ALTER TABLE "GroupFight" ADD COLUMN "mapNpcs" jsonb DEFAULT '[]' NOT NULL;--> statement-breakpoint
-- The initial migration supplies false to existing Organizations on first rollout.
-- This also corrects the default on installations that applied the earlier branch,
-- while preserving their stored administrator choices.
ALTER TABLE "Guild" ALTER COLUMN "groupFightsIncludeIncomplete" SET DEFAULT false;--> statement-breakpoint
CREATE INDEX "GroupFight_endedAt_idx" ON "GroupFight" ("endedAt");
--> statement-breakpoint
-- Preserve classifications for existing catalog fights without changing collection preferences.
UPDATE "GroupFight" AS fight
SET "mapNpcs" = catalog.npcs
FROM (VALUES
  ('Arachnitopia p.6', '[{"name":"Arachniregina Colosseus","npcType":"ELITE2"},{"name":"Rycerz z za małym mieczem","npcType":"ELITE2"}]'::jsonb),
  ('Bandyckie Chowisko - skarbiec', '[{"name":"Renegat Baulus","npcType":"TITAN"}]'::jsonb),
  ('Cenotaf Berserkerów p.1 - sala 2', '[{"name":"Berserker Amuno","npcType":"ELITE2"}]'::jsonb),
  ('Chantli Cuaitla Citlalina', '[{"name":"Cuaitl Citlalin","npcType":"ELITE2"}]'::jsonb),
  ('Chata Teściowej', '[{"name":"Teściowa Rumcajsa","npcType":"ELITE2"}]'::jsonb),
  ('Chata wójta Fistuły p.1', '[{"name":"Wójt Fistuła","npcType":"ELITE2"}]'::jsonb),
  ('Dolina Centaurów', '[{"name":"Centaur Zyfryd","npcType":"ELITE2"}]'::jsonb),
  ('Drzewo Dusz p.2', '[{"name":"Wrzosera","npcType":"ELITE2"},{"name":"Chryzoprenia","npcType":"ELITE2"},{"name":"Cantedewia","npcType":"ELITE2"}]'::jsonb),
  ('Drzewo Życia p.3', '[{"name":"Nymphemonia","npcType":"ELITE2"}]'::jsonb),
  ('Erem Aldiphrina', '[{"name":"Al''diphrin Ilythirahel","npcType":"ELITE2"}]'::jsonb),
  ('Erem Czarnego Słońca p.5', '[{"name":"Grabarz świątynny","npcType":"ELITE2"}]'::jsonb),
  ('Firnowa Grota p.2 s.1', '[{"name":"Wielka Stopa","npcType":"ELITE2"}]'::jsonb),
  ('Głębokie Skałki p.3', '[{"name":"Tollok Atamatu","npcType":"ELITE2"}]'::jsonb),
  ('Głębokie Skałki p.4', '[{"name":"Tollok Utumutu","npcType":"ELITE2"}]'::jsonb),
  ('Gnijące Topielisko', '[{"name":"Arytodam olbrzymi","npcType":"ELITE2"}]'::jsonb),
  ('Grobowiec Seta', '[{"name":"Neferkar Set","npcType":"ELITE2"}]'::jsonb),
  ('Grota Dzikiego Kota', '[{"name":"Mushita","npcType":"ELITE2"}]'::jsonb),
  ('Grota Orczej Hordy p.2 s.3', '[{"name":"Burkog Lorulk","npcType":"ELITE2"}]'::jsonb),
  ('Grota Orczych Szamanów p.3 s.1', '[{"name":"Sheba Orcza Szamanka","npcType":"ELITE2"},{"name":"Shakkru","npcType":"ELITE2"}]'::jsonb),
  ('Grota Samotnych Dusz p.6', '[{"name":"Żelazoręki Ohydziarz","npcType":"ELITE2"}]'::jsonb),
  ('Jama Morskiej Macki p.1 - sala 3', '[{"name":"Morski potwór","npcType":"ELITE2"}]'::jsonb),
  ('Jaskinia Caerbannoga', '[{"name":"Zabójczy Królik","npcType":"TITAN"}]'::jsonb),
  ('Jaskinia Gnollich Szamanów - komnata Kozuga', '[{"name":"Furruk Kozug","npcType":"ELITE2"}]'::jsonb),
  ('Jaskinia Pogardy', '[{"name":"Gobbos","npcType":"ELITE2"}]'::jsonb),
  ('Jaszczurze Korytarze p.2 - sala 5', '[{"name":"Mocny Maddoks","npcType":"ELITE2"}]'::jsonb),
  ('Kamienna Jaskinia - sala 3', '[{"name":"Jotun","npcType":"ELITE2"}]'::jsonb),
  ('Kamienna Strażnica - Sanktuarium', '[{"name":"Goplana","npcType":"ELITE2"}]'::jsonb),
  ('Katakumby Gwałtownej Śmierci', '[{"name":"Chopesz","npcType":"ELITE2"}]'::jsonb),
  ('Komnata Krwawych Obrzędów', '[{"name":"Przyzywacz Demonów","npcType":"TITAN"}]'::jsonb),
  ('Kopalnia Kapiącego Miodu p.2 - sala Owadziej Matki', '[{"name":"Owadzia Matka","npcType":"ELITE2"}]'::jsonb),
  ('Kopalnia Margorii', '[{"name":"Nadzorczyni krasnoludów","npcType":"ELITE2"}]'::jsonb),
  ('Kopalnia Żółtego Kruszcu p.2 - sala 2', '[{"name":"Grubber Ochlaj","npcType":"ELITE2"}]'::jsonb),
  ('Krypty Bezsennych p.3', '[{"name":"Torunia Ankelwald","npcType":"ELITE2"}]'::jsonb),
  ('Krypty Dusz Śniegu p.3 - komnata Lisza', '[{"name":"Lisz","npcType":"ELITE2"}]'::jsonb),
  ('Kryształowa Grota - Sala Smutku', '[{"name":"Królowa Śniegu","npcType":"ELITE2"}]'::jsonb),
  ('Krzaczasta Grota - sala główna', '[{"name":"Silvanasus","npcType":"ELITE2"}]'::jsonb),
  ('Kuźnia Worundriela - Komnata Żaru', '[{"name":"Mistrz Worundriel","npcType":"ELITE2"}]'::jsonb),
  ('Laboratorium Adariel', '[{"name":"Adariel","npcType":"ELITE2"}]'::jsonb),
  ('Las Tropicieli', '[{"name":"Kotołak Tropiciel","npcType":"ELITE2"}]'::jsonb),
  ('Lazurytowa Grota p.4', '[{"name":"Foverk Turrim","npcType":"ELITE2"}]'::jsonb),
  ('Lokum Złych Goblinów - pracownia', '[{"name":"Versus Zoons","npcType":"TITAN"}]'::jsonb),
  ('Lokum Złych Goblinów - warsztat', '[{"name":"Goons Asterus","npcType":"ELITE2"}]'::jsonb),
  ('Mała Twierdza - sala główna', '[{"name":"Fodug Zolash","npcType":"ELITE2"}]'::jsonb),
  ('Margoria - Sala Królewska', '[{"name":"Morthen","npcType":"ELITE2"}]'::jsonb),
  ('Migotliwa Pieczara', '[{"name":"Dziewicza Orlica","npcType":"TITAN"}]'::jsonb),
  ('Mokra Grota p.2', '[{"name":"Agar","npcType":"ELITE2"}]'::jsonb),
  ('Namiot Kambiona', '[{"name":"Kambion","npcType":"ELITE2"}]'::jsonb),
  ('Namiot Vari Krugera', '[{"name":"Vari Kruger","npcType":"ELITE2"}]'::jsonb),
  ('Nawiedzone Kazamaty p.4', '[{"name":"Duch Władcy Klanów","npcType":"ELITE2"}]'::jsonb),
  ('Nora Jaszczurzych Koszmarów - źródło', '[{"name":"Maddok Magua","npcType":"TITAN"}]'::jsonb),
  ('Ogrza Kawerna p.4', '[{"name":"Ogr Stalowy Pazur","npcType":"ELITE2"}]'::jsonb),
  ('Ołtarz Pajęczej Bogini', '[{"name":"Marlloth Malignitas","npcType":"ELITE2"}]'::jsonb),
  ('Opuszczony statek - pokład', '[{"name":"Krab pustelnik","npcType":"ELITE2"}]'::jsonb),
  ('Piaskowa Pułapka - Grota Piaskowej Śmierci', '[{"name":"Stworzyciel","npcType":"ELITE2"}]'::jsonb),
  ('Piaszczysta Grota p.1 - sala 2', '[{"name":"Eol","npcType":"ELITE2"}]'::jsonb),
  ('Pieczara Kwiku - sala 2', '[{"name":"Tyrtajos","npcType":"ELITE2"}]'::jsonb),
  ('Piramida Pustynnego Władcy p.3', '[{"name":"Ozirus Władca Hieroglifów","npcType":"ELITE2"}]'::jsonb),
  ('Podmokła Dolina', '[{"name":"Władca rzek","npcType":"ELITE2"}]'::jsonb),
  ('Podziemia Zniszczonej Wieży p.5', '[{"name":"Jertek Moxos","npcType":"ELITE2"}]'::jsonb),
  ('Potępione Zamczysko - pracownia', '[{"name":"Pogardliwa Sybilla","npcType":"ELITE2"}]'::jsonb),
  ('Przeklęta Strażnica - podziemia p.2 s.1', '[{"name":"Shae Phu","npcType":"ELITE2"}]'::jsonb),
  ('Przerażające Sypialnie', '[{"name":"Sadolia Nadzorczyni Hurys","npcType":"ELITE2"}]'::jsonb),
  ('Przysiółek Valmirów', '[{"name":"Breheret Żelazny Łeb","npcType":"ELITE2"}]'::jsonb),
  ('Sala Królewska', '[{"name":"Lusgrathera Królowa Pramatka","npcType":"ELITE2"}]'::jsonb),
  ('Sala Lodowej Magii', '[{"name":"Artenius","npcType":"ELITE2"}]'::jsonb),
  ('Sala Mroźnych Strzał', '[{"name":"Furion","npcType":"ELITE2"}]'::jsonb),
  ('Sala Mroźnych Szeptów', '[{"name":"Zorin","npcType":"ELITE2"}]'::jsonb),
  ('Sala Rady Orków', '[{"name":"Bragarth Myśliwy Dusz","npcType":"ELITE2"},{"name":"Fursharag Pożeracz Umysłów","npcType":"ELITE2"},{"name":"Ziuggrael Strażnik Królowej","npcType":"ELITE2"}]'::jsonb),
  ('Sala Skaryfikacji Grzeszników', '[{"name":"Sataniel Skrytobójca","npcType":"ELITE2"}]'::jsonb),
  ('Sala Tronowa', '[{"name":"Tanroth","npcType":"TITAN"}]'::jsonb),
  ('Sala Tysiąca Świec', '[{"name":"Zufulus Smakosz Serc","npcType":"ELITE2"}]'::jsonb),
  ('Sala Zrujnowanej Świątyni', '[{"name":"Barbatos Smoczy Strażnik","npcType":"TITAN"}]'::jsonb),
  ('Sale Rozdzierania', '[{"name":"Bergermona Krwawa Hrabina","npcType":"ELITE2"}]'::jsonb),
  ('Schowek na Łupy', '[{"name":"Zorg Jednooki Baron","npcType":"ELITE2"}]'::jsonb),
  ('Skalne Cmentarzysko p.4', '[{"name":"Łowca czaszek","npcType":"ELITE2"}]'::jsonb),
  ('Skalne Turnie', '[{"name":"Tollok Shimger","npcType":"ELITE2"}]'::jsonb),
  ('Skarpa Trzech Słów', '[{"name":"Pięknotka Mięsożerna","npcType":"ELITE2"}]'::jsonb),
  ('Stare Wyrobisko p.3', '[{"name":"Razuglag Oklash","npcType":"ELITE2"}]'::jsonb),
  ('Starodrzew Przedwiecznych p.2', '[{"name":"Cerasus","npcType":"ELITE2"}]'::jsonb),
  ('Stary Kupiecki Trakt', '[{"name":"Szczęt alias Gładki","npcType":"ELITE2"}]'::jsonb),
  ('Szlamowe Kanały p.2 - sala 3', '[{"name":"Mysiur Myświórowy Król","npcType":"ELITE2"}]'::jsonb),
  ('Świątynia Andarum - zbrojownia', '[{"name":"Podły zbrojmistrz","npcType":"ELITE2"}]'::jsonb),
  ('Świątynia Hebrehotha - sala czciciela', '[{"name":"Chaegd Agnrakh","npcType":"ELITE2"}]'::jsonb),
  ('Świątynia Hebrehotha - sala ofiary', '[{"name":"Vaenra Charkhaam","npcType":"ELITE2"}]'::jsonb),
  ('Tajemnicza Siedziba', '[{"name":"Annaniel Wysysacz Marzeń","npcType":"ELITE2"},{"name":"Gothardus Kolekcjoner Głów","npcType":"ELITE2"}]'::jsonb),
  ('Teotihuacan', '[{"name":"Tezcatlipoca","npcType":"TITAN"}]'::jsonb),
  ('Twierdza Rogogłowych - Sala Byka', '[{"name":"Borgoros Garamir III","npcType":"ELITE2"}]'::jsonb),
  ('Ukryta Grota Morskich Diabłów - magazyn', '[{"name":"Młody Jack Truciciel","npcType":"ELITE2"}]'::jsonb),
  ('Ukryta Grota Morskich Diabłów - siedziba', '[{"name":"Helga Opiekunka Rumu","npcType":"ELITE2"}]'::jsonb),
  ('Ukryta Grota Morskich Diabłów - skarbiec', '[{"name":"Henry Kaprawe Oko","npcType":"ELITE2"}]'::jsonb),
  ('Urwisko Vapora', '[{"name":"Terrozaur","npcType":"ELITE2"}]'::jsonb),
  ('Wschodni Mictlan p.9', '[{"name":"Quetzalcoatl","npcType":"ELITE2"}]'::jsonb),
  ('Wulkan Politraki - Piekielne Czeluście', '[{"name":"Piekielny Arcymag","npcType":"TITAN"}]'::jsonb),
  ('Wulkan Politraki p.1 - sala 3', '[{"name":"Ifryt","npcType":"ELITE2"}]'::jsonb),
  ('Wylęgarnia Choukkerów p.1', '[{"name":"Choukker","npcType":"ELITE2"}]'::jsonb),
  ('Zabłocona Jama p.2 - Sala Błotnistych Odmętów', '[{"name":"Miłośnik rycerzy","npcType":"ELITE2"}]'::jsonb),
  ('Zabłocona Jama p.2 - Sala Duszącej Stęchlizny', '[{"name":"Miłośnik łowców","npcType":"ELITE2"}]'::jsonb),
  ('Zabłocona Jama p.2 - Sala Magicznego Błota', '[{"name":"Miłośnik magii","npcType":"ELITE2"}]'::jsonb),
  ('Zachodni Mictlan p.9', '[{"name":"Yaotl","npcType":"ELITE2"}]'::jsonb),
  ('Zagrzybiałe Ścieżki p.3', '[{"name":"Gnom Figlid","npcType":"ELITE2"}]'::jsonb),
  ('Zalana Grota', '[{"name":"Czempion Furboli","npcType":"ELITE2"}]'::jsonb),
  ('Zapomniany Święty Gaj p.3', '[{"name":"Leśne Widmo","npcType":"ELITE2"}]'::jsonb),
  ('Złota Góra p.2 s.1', '[{"name":"Tolypeutes","npcType":"ELITE2"}]'::jsonb),
  ('Źródło Wspomnień', '[{"name":"Łowczyni Wspomnień","npcType":"TITAN"}]'::jsonb),
  ('Źródło Zakorzenionego Ludu', '[{"name":"Dendroculus","npcType":"ELITE2"}]'::jsonb)
) AS catalog(name, npcs)
WHERE fight."mapName" = catalog.name AND fight."mapNpcs" = '[]'::jsonb;
