apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: kamilwronka7/lootlog-api:latest
          resources:
            requests:
              memory: '768Mi'
              cpu: '500m'
            limits:
              memory: '1024Mi'
              cpu: '900m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-api-secrets
            - name: POSTGRESQL_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: postgresqlConnectionUri
            - name: AXIOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: axiomToken
            - name: AXIOM_DATASET
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: axiomDataset
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: rabbitmqUri
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'

          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 4000
          # readinessProbe:
          #   tcpSocket:
          #     port: 4000
          #   initialDelaySeconds: 50
          #   periodSeconds: 20
