apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: kamilwronka7/lootlog-api:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1.5Gi"
              cpu: "2000m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1200"
            - name: PORT
              value: "4000"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-api-secrets
            - name: POSTGRESQL_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: postgresqlConnectionUri
            - name: AXIOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: axiomToken
            - name: AXIOM_DATASET
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: axiomDataset
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: rabbitmqUri
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: dragonfly
            - name: REDIS_PORT
              value: "6379"
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: lootlog-api-secrets
                  key: authServiceUrl
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
