apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      serviceAccountName: search
      containers:
        - name: search
          image: kamilwronka7/lootlog-search:latest
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '384Mi'
              cpu: '300m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-search-secrets
            - name: POSTGRESQL_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: postgresqlConnectionUri
            - name: AXIOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: axiomToken
            - name: AXIOM_DATASET
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: axiomDataset
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: rabbitmqUri
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-search-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
