apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
        - name: gateway
          image: kamilwronka7/lootlog-gateway:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=3072"
            - name: PORT
              value: "4000"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-gateway-secrets
            - name: SERVICE_NAME
              value: "gateway"
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: rabbitmqUri
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: dragonfly
            - name: REDIS_PORT
              value: "6379"
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: apiUrl
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
