apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
        - name: gateway
          image: kamilwronka7/lootlog-gateway:latest
          resources:
            requests:
              memory: '384Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '300m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-gateway-secrets
            - name: SERVICE_NAME
              value: 'gateway'
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: rabbitmqUri
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
