apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
        - name: gateway
          image: kamilwronka7/lootlog-gateway:latest
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '384Mi'
              cpu: '300m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-gateway-secrets
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: rabbitmqUri
            - name: AUTH_ISSUER
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: authIssuer
            - name: AUTH_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: authAudience
            - name: AUTH_JWKS_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-gateway-secrets
                  key: jwksUri

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
