apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
spec:
  selector:
    matchLabels:
      app: activity
  template:
    metadata:
      labels:
        app: activity
    spec:
      serviceAccountName: activity
      containers:
        - name: activity
          image: kamilwronka7/lootlog-activity:latest

          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          ports:
            - name: container-port
              containerPort: 4000

          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=800"

            - name: PORT
              value: "4000"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-activity-secrets
            - name: SERVICE_NAME
              value: activity-service
            - name: POSTGRESQL_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: postgresqlConnectionUri
            - name: AXIOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: axiomToken
            - name: AXIOM_DATASET
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: axiomDataset
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: redisUsername
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: redisPassword
            - name: REDIS_HOST
              value: dragonfly
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: rabbitmqUri
            - name: API_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: apiServiceUrl
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: otelExporterOtlpEndpoint
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: otelExporterOtlpHeaders
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: "env,host,os,process"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: SERVICE_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: lootlog-activity-secrets
                  key: serviceNamespace

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
