apiVersion: v1
kind: Service
metadata:
  name: activity
  labels:
    app: activity
    service: activity
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4027
      targetPort: 4027
      protocol: TCP
      name: http
  selector:
    app: activity
