namespace: lootlog-prod
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: prod-d37d130640ac469652a5541cdebc5cbc493cc698
namePrefix: prod-
