namespace: lootlog-prod
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: prod-4c950ab10cf97e635fe0ffdd0730480f11b6703e
namePrefix: prod-
