namespace: lootlog-prod
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: prod-ddaeb7344223541fd5ca179e725d99e44391bf25
namePrefix: prod-
