namespace: lootlog-dev
resources:
  - ../../base/battlelog-service
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-battlelog-service
    newTag: dev-e6596dc82b5aefc7ac4384988990a1438bb543ee
namePrefix: dev-
