namespace: lootlog-dev
resources:
  - ../../base/battlelog-service
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-battlelog-service
    newTag: dev-bfdde21c7d120ddfdcda6a070214c6e5fe3931f5
namePrefix: dev-
