namespace: lootlog-dev
resources:
  - ../../base/battlelog-service
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-battlelog-service
    newTag: dev-dfd5c86fe55540e7187411e83bcd5cb77798dac2
namePrefix: dev-
