export enum ErrorKey {
  MEMBER_TTL_ACTIVE = "MEMBER_TTL_ACTIVE",
  MEMBER_ALREADY_DEACTIVATED = "MEMBER_ALREADY_DEACTIVATED",
  DISCORD_MEMBER_VERIFICATION_UNAVAILABLE = "DISCORD_MEMBER_VERIFICATION_UNAVAILABLE",
  BULK_REFRESH_RATE_LIMIT_ACTIVE = "BULK_REFRESH_RATE_LIMIT_ACTIVE",
  REFRESH_JOB_NOT_FOUND = "REFRESH_JOB_NOT_FOUND",
}
