/**
 * Regenerates src/group-fight-maps.ts from the margoworld NPC catalog kept in
 * packages/cli (scraped from https://margoworld.pl/npc/elite2 and /npc/titan).
 *
 * Usage: bun scripts/generate-group-fight-maps.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { isRecord } from "@lootlog/schema/records";
import { NpcTypeEnum } from "@lootlog/schema/npc-type";
import { getNpcTypeByWt } from "../src/npc-type";

const source = resolve(import.meta.dir, "../../cli/src/mocks/data/npcs.json");
const target = resolve(import.meta.dir, "../src/group-fight-maps.ts");

const npcs: unknown = JSON.parse(readFileSync(source, "utf8"));
if (!Array.isArray(npcs)) throw new Error("Expected an NPC catalog array");

type CatalogNpc = { name: string; npcType: "ELITE2" | "TITAN" };
const entries = new Map<string, Map<string, CatalogNpc>>();
for (const npc of npcs) {
  if (
    !isRecord(npc) ||
    typeof npc.name !== "string" ||
    typeof npc.wt !== "number" ||
    (npc.location !== undefined && typeof npc.location !== "string")
  ) {
    throw new Error("Invalid NPC catalog entry");
  }
  const npcType = getNpcTypeByWt(NpcTypeEnum, npc.wt);
  if (
    !npc.location ||
    (npcType !== NpcTypeEnum.ELITE2 && npcType !== NpcTypeEnum.TITAN)
  )
    continue;
  const location = npc.location.replace(/\s+/g, " ").trim();
  const names = entries.get(location) ?? new Map<string, CatalogNpc>();
  names.set(`${npcType}:${npc.name}`, { name: npc.name, npcType });
  entries.set(location, names);
}

const sorted = [...entries.entries()].sort(([left], [right]) =>
  left.localeCompare(right, "pl"),
);

const lines = sorted.map(
  ([location, names]) =>
    `  [${JSON.stringify(location)}, ${JSON.stringify([...names.values()])}],`,
);

writeFileSync(
  target,
  `// Generated by scripts/generate-group-fight-maps.ts from packages/cli mock NPC
// data (margoworld.pl Elite II and Titan pages). Do not edit by hand.
import { normalizeGroupFightName } from "./group-fights.js";
import { getNpcTypeByWt } from "./npc-type.js";
import { NpcTypeEnum } from "@lootlog/schema/npc-type";

export type GroupFightMapNpc = Readonly<{ name: string; npcType: "ELITE2" | "TITAN" }>;

const catalog: ReadonlyArray<readonly [string, readonly GroupFightMapNpc[]]> = [
${lines.join("\n")}
];

/** In-game map names that host at least one Elite II or Titan NPC. */
export const GROUP_FIGHT_MAP_NAMES: ReadonlyArray<string> = catalog.map(([name]) => name);

const normalizedGroupFightMapNpcs = new Map(
  catalog.map(([name, npcs]) => [normalizeGroupFightName(name), npcs]),
);

export const getGroupFightMapNpcs = (mapName: string | null | undefined): readonly GroupFightMapNpc[] =>
  typeof mapName === "string"
    ? normalizedGroupFightMapNpcs.get(normalizeGroupFightName(mapName)) ?? []
    : [];

export const isGroupFightMap = (mapName: string | null | undefined): boolean =>
  getGroupFightMapNpcs(mapName).length > 0;

export const getGroupFightNpcType = (weight: number | undefined): GroupFightMapNpc["npcType"] | null => {
  if (weight === undefined || !Number.isFinite(weight)) return null;
  const npcType = getNpcTypeByWt(NpcTypeEnum, weight);
  return npcType === NpcTypeEnum.ELITE2 || npcType === NpcTypeEnum.TITAN ? npcType : null;
};

export const isGroupFightNpcWeight = (weight: number | undefined): boolean =>
  getGroupFightNpcType(weight) !== null;

/** Qualifies a red map using the catalog or an NPC observed in this map epoch. */
export const isQualifyingGroupFightMap = (input: {
  readonly name: string | null | undefined;
  readonly pvp: number | null | undefined;
  readonly observedNpcWeight?: number;
}): boolean => {
  if (input.pvp !== 2) return false;
  if (isGroupFightMap(input.name)) return true;
  return isGroupFightNpcWeight(input.observedNpcWeight);
};
`,
);

console.log(`Wrote ${sorted.length} maps to ${target}`);
