namespace: lootlog-dev
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: dev-5e289fb56629f1f6c815e41d5832ff5ce3b48933
namePrefix: dev-
