namespace: lootlog-dev
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: dev-d0f2ada2109d2c990d231cbf0a49e07fc52eeb7a
namePrefix: dev-
