namespace: lootlog-dev
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: dev-36223d690cf93f57791eee4329d9c06cc4230e74
namePrefix: dev-
