namespace: lootlog-dev
resources:
  - ../../base/api
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-api
    newTag: dev-7f17fe51ab448b89984672e20508efcbce0d40c7
namePrefix: dev-
