-- AlterTable
ALTER TABLE "EventKillPoint" ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "basePoints" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "EventPointsEditHistory" ALTER COLUMN "previousPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "newPoints" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "EventRanking" ALTER COLUMN "totalPoints" SET DEFAULT 0,
ALTER COLUMN "totalPoints" SET DATA TYPE DOUBLE PRECISION;
