http:
  routers:
    landing:
      rule: "Path(`/`) || PathPrefix(`/_next/`) || PathPrefix(`/favicon.ico`) || PathPrefix(`/static/`) || Path(`/terms-of-service`) || Path(`/privacy-policy`) || PathPrefix(`/screenshots/`)"
      service: "landing"
      priority: 30
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"

    gateway:
      rule: "PathPrefix(`/gateway`)"
      service: "gateway"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiCompress"
        - "apiForwardAuth"
      priority: 20
      entryPoints:
        - "web"

    auth:
      rule: "PathPrefix(`/api/auth`)"
      service: "auth"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiCompress"
      priority: 10
      entryPoints:
        - "web"

    search:
      rule: "PathPrefix(`/api/search`)"
      service: "search"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      priority: 10
      entryPoints:
        - "web"

    api:
      rule: "PathPrefix(`/api/lootlog`)"
      service: "api"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      priority: 10
      entryPoints:
        - "web"

    web-client:
      rule: "PathPrefix(`/`)"
      service: "web-client"
      priority: 1
      middlewares:
        - "cors"
        - "apiCompress"
      entryPoints:
        - "web"

    # web-client-ws:
    #   rule: "HeaderRegexp(`Upgrade`, `(?i)websocket`)"
    #   service: "web-client"
    #   entryPoints:
    #     - "web"
    #   priority: 100
    #   middlewares:
    #     - "cors"
    #     - "apiCompress"
        
  services:
    web-client:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3000"
    landing:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3003"
    auth:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4001"
    search:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4002"
    api:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4003"
    gateway:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4004"
  middlewares:
    apiStripPrefix:
      stripPrefix:
        prefixes:
          - "/api/auth"
          - "/api/search"
          - "/api/lootlog"
          - "/gateway"
    apiForwardAuth:
      forwardAuth:
        address: "http://host.docker.internal:4001/auth/verify"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
        authRequestHeaders:
        - "Authorization"
        - "Cookie"
    apiCompress:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain
    cors:
      headers:
        accessControlAllowOriginListRegex:
          - "^(.+)\\.margonem\\.(pl|com)$"
          - "^http://localhost$"
          - "^http://localhost:3001$"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 86400
        addVaryHeader: true
        accessControlAllowCredentials: true