http:
  routers:
    auth:
      rule: "PathPrefix(`/api/auth`)"
      service: "auth"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiCompress"
      entryPoints:
        - "web"
    search:
      rule: "PathPrefix(`/api/search`)"
      service: "search"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      entryPoints:
        - "web"
    api:
      rule: "PathPrefix(`/api/lootlog`)"
      service: "api"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      entryPoints:
        - "web"
    gateway:
      rule: "PathPrefix(`/gateway`)"
      service: "gateway"
      middlewares:
        - "cors"
        - "apiStripPrefix"
        - "apiCompress"
      entryPoints:
        - "web"
    landing:
      rule: "Path(`/`) || PathPrefix(`/_next/`)"
      service: "landing"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
    web-client:
      rule: "PathRegexp(`/(.+)`)"
      service: "web-client"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
    web-client-ws:
      rule: "HeaderRegexp(`Upgrade`, `(?i)^websocket$`)"
      service: "web-client"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
        
  services:
    web-client:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3000"
    landing:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3001"
    auth:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4001"
    search:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4002"
    api:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4003"
    gateway:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4004"
  middlewares:
    apiStripPrefix:
      stripPrefix:
        prefixes:
          - "/api/auth"
          - "/api/search"
          - "/api/lootlog"
          - "/gateway"
    apiForwardAuth:
      forwardAuth:
        address: "http://host.docker.internal:4001/verify-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
        authRequestHeaders:
        - "Authorization"
        - "Cookie"
    apiCompress:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain
    cors:
      headers:
        accessControlAllowOriginListRegex:
          - "^(.+)\\.margonem\\.(pl|com)$"
          - "^http://localhost$"
          - "^http://localhost:3001$"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 86400
        addVaryHeader: true
        accessControlAllowCredentials: true