export const GatewayConfig = {
  SOCKET_PING_INTERVAL_MS: 25000,
  SOCKET_PING_TIMEOUT_MS: 60000,
  REVALIDATION_INTERVAL_MS: 5 * 60 * 1000,
  MAX_USERS_PER_REVALIDATION_CYCLE: 100,
  DELAY_BETWEEN_USERS_MS: 100,
  DEFAULT_MAX_RETRIES: 3,
} as const;
