export enum ErrorKey {
  PAGINATION_LIMIT_TOO_HIGH = 'PAGINATION_LIMIT_TOO_HIGH',
  CANT_UPDATE_LOOT = 'CANT_UPDATE_LOOT',
  MISSING_LOOT_SHARE = 'MISSING_LOOT_SHARE',
  MISSING_LOOT_SHARE_ITEM_OR_PLAYER = 'MISSING_LOOT_SHARE_ITEM_OR_PLAYER',
  CANT_CREATE_COMMENT = 'CANT_CREATE_COMMENT',
  CANT_DELETE_LOOT = 'CANT_DELETE_LOOT',
  GUILD_NOT_WHITELISTED_FOR_CHARACTER = 'GUILD_NOT_WHITELISTED_FOR_CHARACTER',
  GUILD_CONFIG_REJECTS_LOOT = 'GUILD_CONFIG_REJECTS_LOOT',
  LOOT_CREATION_CONFLICT = 'LOOT_CREATION_CONFLICT',
}
