export enum ErrorKey {
  PAGINATION_LIMIT_TOO_HIGH = 'PAGINATION_LIMIT_TOO_HIGH',
  CANT_UPDATE_LOOT = 'CANT_UPDATE_LOOT',
  MISSING_LOOT_SHARE = 'MISSING_LOOT_SHARE',
  MISSING_LOOT_SHARE_ITEM_OR_PLAYER = 'MISSING_LOOT_SHARE_ITEM_OR_PLAYER',
}
