export enum ErrorKey {
  PAGINATION_LIMIT_TOO_HIGH = 'PAGINATION_LIMIT_TOO_HIGH',
  CANT_UPDATE_LOOT = 'CANT_UPDATE_LOOT',
  MISSING_LOOT_SHARE = 'MISSING_LOOT_SHARE',
  MISSING_LOOT_SHARE_ITEM_OR_PLAYER = 'MISSING_LOOT_SHARE_ITEM_OR_PLAYER',
  CANT_CREATE_COMMENT = 'CANT_CREATE_COMMENT',
  CANT_DELETE_LOOT = 'CANT_DELETE_LOOT',
  NO_GUILD_CONFIG_ACCEPTS_THIS_LOOT = 'NO_GUILD_CONFIG_ACCEPTS_THIS_LOOT',
  NO_GUILDS_ON_THE_CHARACTER_WHITELIST = 'NO_GUILDS_ON_THE_CHARACTER_WHITELIST',
  NPC_WT_TOO_LOW = 'NPC_WT_TOO_LOW',
}
