export interface RajController {
  init(): void;
  addSrajClass(kindOfSrajClass: string, moduleName: string): void;
  getAllSrajClass(): any;
  initRajFullJSONReplacer(): void;
  callSrajFromEngine(data: any[], kind: any): void;
  parseJSON(d: string, exception?: any[], additionalData?: any): void;
  parseObject(data: any, exception: any[], additionalData: any, callback?: any): void;
  setAddSrajToQueue(addSrajToQueue: boolean): void;
  setAddSrajToCaseQueue(addSrajToCaseQueue: boolean): void;
  addToSrajQueue(data: any, exception: any, additionalData: any, callback: any): void;
  addToCaseSrajQueue(callback: any): void;
  clearRajCaseQueue(): void;
  callSrajQueue(): void;
  callSrajCaseQueue(counter: number): void;
  clearRajQueue(): void;
  updateRajObject(data: any, exception: any, additionalData: any, callback: any): void;
  manageSrajBeforeSuccessRespond(): void;
  manageSrajAfterSuccessRespond(): void;
  initDispatcher(): void;
  checkRajKeyExist(rajKey: string): boolean;
  
  // Test methods
  testNight(): void;
  testNightWithEmptyList(): void;
  testRemoveNight(): void;
  testRemoveFog(): void;
  testPreloadImage(): void;
  testPreloadImage2(): void;
  createTextFakeNpc(): void;
  createHeroDirFakeNpc(): void;
  createHeroDirFakeBug(): void;
  testTextBlario(): void;
  testTextBlarioBeforeAfter(): void;
  testCharacterEffetsTintBlarioBeforeAfter(): void;
  testCharacterEffetsIconBlarioBeforeAfter(): void;
  testTextBlarioRandomTrue(): void;
  testIconEffectBehind(): void;
  testIconEffect(): void;
  testStickMapTextEffect(): void;
  testStickMapBlackTextEffect(): void;
  testRandomTextEffect(): void;
  testTextEffect(): void;
  testRemoveFakeNpc(): void;
  testTutorialItem(): void;
  testMove(): void;
  testMoveCase(): void;
  testTalkTutorial(): void;
  testAttackNpcTutorial(): void;
  testPreventRepeatAttackNpcTutorial(): void;
  testTutorialExternalProperties(): void;
  testTutorialBattleSkill(): void;
  testTutorialBattleSkillAbsoluteFinishEndBattle(): void;
  testTutorialItemsInBasket(): void;
  testTutorialItemsInBasketCloseShop(): void;
  testTutorialStepByStep(): void;
  testTutorialStepByStepCloseShop(): void;
  testTutorialRecipeWidget(): void;
  testTutorialOpenWindow(): void;
  testTutorialClickRecipeOnList(): void;
  testTutorialClickUseRecipe(): void;
  testTutorialBattleEventsOnStartFight(): void;
  testTutorialWindowEventsOnOpen(): void;
  testTutorialWindowEventsOnUpdate(): void;
  testTutorialWindowEventsOnUpdate2(): void;
  testNightCase(): void;
  testNightCaseMapExternalPropertiesRefresh(): void;
  testNightMinAlpha(): void;
  testCreateProgrammer10(): void;
  testBubble(): void;
  testRemoveProgrammer10(): void;
  testCreateProgrammer11(): void;
  testRemoveProgrammer11(): void;
  testCreateForceProgrammer11(): void;
  testGetTemplate(): void;
  testSrajWindow0(): void;
  testSrajWindow1(): void;
  testSrajWindow2(): void;
  testSrajWindow3(): void;
  testSrajWindow4(): void;
  testSrajWindow5(): void;
  testSrajWindow6(): void;
  testSrajWindow7(): void;
  testSrajWindow8(): void;
  removeSrajWindow(): void;
  testExtraLight(): void;
  testExtraLightRemove(): void;

  [key: string]: any;
}

export interface RajWindowManager {
  init(): void;
  updateData(data: any, additionalData: any): void;
  removeWindow(id: any): void;
  onClear(): void;
  checkWindowListExist(id: any): boolean;
  [key: string]: any;
}
