CREATE TABLE "battle_warriors" (
	"id" text PRIMARY KEY,
	"battleId" text NOT NULL,
	"originalId" text NOT NULL,
	"name" text NOT NULL,
	"lvl" integer NOT NULL,
	"prof" text NOT NULL,
	"icon" text NOT NULL,
	"team" integer NOT NULL,
	"turns" integer NOT NULL,
	"turnsLost" integer DEFAULT 0 NOT NULL,
	"steps" integer DEFAULT 0 NOT NULL,
	"normalAttacks" integer DEFAULT 0 NOT NULL,
	"spellsUsed" integer DEFAULT 0 NOT NULL,
	"spellsUsedMap" jsonb DEFAULT '"{}"' NOT NULL,
	"isDead" boolean DEFAULT false NOT NULL,
	"surrendered" boolean DEFAULT false NOT NULL,
	"fled" boolean DEFAULT false NOT NULL,
	"maxHp" integer DEFAULT 0 NOT NULL,
	"damageDealt" integer DEFAULT 0 NOT NULL,
	"distanceDamage" integer DEFAULT 0 NOT NULL,
	"meleeDamage" integer DEFAULT 0 NOT NULL,
	"auxiliaryDamage" integer DEFAULT 0 NOT NULL,
	"fireDamage" integer DEFAULT 0 NOT NULL,
	"frostDamage" integer DEFAULT 0 NOT NULL,
	"lightningDamage" integer DEFAULT 0 NOT NULL,
	"thirdAttDamage" integer DEFAULT 0 NOT NULL,
	"damageDealtAfterDefensive" integer DEFAULT 0 NOT NULL,
	"damageDealtAfterDefensivePercentage" double precision DEFAULT 0 NOT NULL,
	"damageTaken" integer DEFAULT 0 NOT NULL,
	"distanceDamageTaken" integer DEFAULT 0 NOT NULL,
	"meleeDamageTaken" integer DEFAULT 0 NOT NULL,
	"auxiliaryDamageTaken" integer DEFAULT 0 NOT NULL,
	"fireDamageTaken" integer DEFAULT 0 NOT NULL,
	"frostDamageTaken" integer DEFAULT 0 NOT NULL,
	"lightningDamageTaken" integer DEFAULT 0 NOT NULL,
	"thirdAttDamageTaken" integer DEFAULT 0 NOT NULL,
	"flatDamageTaken" integer DEFAULT 0 NOT NULL,
	"rageDamageDealt" integer DEFAULT 0 NOT NULL,
	"trueDamageDealt" integer DEFAULT 0 NOT NULL,
	"trueDamageTaken" integer DEFAULT 0 NOT NULL,
	"stigmaDamageDealt" integer DEFAULT 0 NOT NULL,
	"stigmaDamageTaken" integer DEFAULT 0 NOT NULL,
	"passiveHealing" integer DEFAULT 0 NOT NULL,
	"activeHealing" integer DEFAULT 0 NOT NULL,
	"armorPierces" integer DEFAULT 0 NOT NULL,
	"criticalHits" integer DEFAULT 0 NOT NULL,
	"reducedArmor" integer DEFAULT 0 NOT NULL,
	"reducedPoisonResistance" integer DEFAULT 0 NOT NULL,
	"magicResistanceDestroyed" integer DEFAULT 0 NOT NULL,
	"evasions" integer DEFAULT 0 NOT NULL,
	"attacksEvaded" integer DEFAULT 0 NOT NULL,
	"counters" integer DEFAULT 0 NOT NULL,
	"fastArrows" integer DEFAULT 0 NOT NULL,
	"blocks" integer DEFAULT 0 NOT NULL,
	"attacksBlocked" integer DEFAULT 0 NOT NULL,
	"blockedDamage" integer DEFAULT 0 NOT NULL,
	"woundDamageTaken" integer DEFAULT 0 NOT NULL,
	"poisonDamageTaken" integer DEFAULT 0 NOT NULL,
	"injureDamageTaken" integer DEFAULT 0 NOT NULL,
	"injures" integer DEFAULT 0 NOT NULL,
	"critWoundDamageTaken" integer DEFAULT 0 NOT NULL,
	"firePassiveDamageTaken" integer DEFAULT 0 NOT NULL,
	"lightningPassiveDamageTaken" integer DEFAULT 0 NOT NULL,
	"destroyedEnergy" integer DEFAULT 0 NOT NULL,
	"destroyedMana" integer DEFAULT 0 NOT NULL,
	"regeneratedEnergy" integer DEFAULT 0 NOT NULL,
	"regeneratedMana" integer DEFAULT 0 NOT NULL,
	"reflectedDamage" integer DEFAULT 0 NOT NULL,
	"reflectedDamageTaken" integer DEFAULT 0 NOT NULL,
	"legbons" integer DEFAULT 0 NOT NULL,
	"legbonCurse" integer DEFAULT 0 NOT NULL,
	"legbonCleanse" integer DEFAULT 0 NOT NULL,
	"legbonLastheal" integer DEFAULT 0 NOT NULL,
	"legbonLasthealValue" integer DEFAULT 0 NOT NULL,
	"legbonGlare" integer DEFAULT 0 NOT NULL,
	"legbonHolytouch" integer DEFAULT 0 NOT NULL,
	"legbonHolytouchValue" integer DEFAULT 0 NOT NULL,
	"legbonCritredValue" integer DEFAULT 0 NOT NULL,
	"legbonFacadeValue" integer DEFAULT 0 NOT NULL,
	"legbonPunctureValue" integer DEFAULT 0 NOT NULL,
	"legbonVerycrit" integer DEFAULT 0 NOT NULL,
	"legbonAnguish" integer DEFAULT 0 NOT NULL,
	"legbonAnguishDamageTaken" integer DEFAULT 0 NOT NULL,
	"ph" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "battles" (
	"id" text PRIMARY KEY,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"public" boolean DEFAULT false NOT NULL,
	"userId" text NOT NULL,
	"accountId" text NOT NULL,
	"characterId" text NOT NULL,
	"world" text NOT NULL,
	"duration" double precision NOT NULL,
	"type" text NOT NULL,
	"winner" text NOT NULL,
	"loser" text NOT NULL,
	"winningTeam" integer NOT NULL,
	"losingTeam" integer NOT NULL,
	"honorPoints" integer DEFAULT 0 NOT NULL,
	"hasFlee" boolean DEFAULT false NOT NULL,
	"matchmaking" boolean DEFAULT false NOT NULL,
	"statistics" jsonb NOT NULL,
	"difficultyRank" integer,
	"result" integer,
	"ratingDelta" integer,
	"opponentLvl" integer,
	"opponentOplvl" integer,
	"opponentRating" integer,
	"rating" integer,
	"status" integer
);
--> statement-breakpoint
CREATE TABLE "user_characters" (
	"id" text PRIMARY KEY,
	"userId" text NOT NULL,
	"characterId" text NOT NULL,
	"name" text NOT NULL,
	"world" text NOT NULL,
	"icon" text DEFAULT '' NOT NULL,
	"lastSeenAt" timestamp DEFAULT now() NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "battle_warriors_originalId_idx" ON "battle_warriors" ("originalId");--> statement-breakpoint
CREATE INDEX "battle_warriors_name_idx" ON "battle_warriors" ("name");--> statement-breakpoint
CREATE INDEX "battle_warriors_battleId_team_idx" ON "battle_warriors" ("battleId","team");--> statement-breakpoint
CREATE INDEX "battles_userId_createdAt_idx" ON "battles" ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "battles_world_createdAt_idx" ON "battles" ("world","createdAt");--> statement-breakpoint
CREATE INDEX "battles_userId_world_createdAt_idx" ON "battles" ("userId","world","createdAt");--> statement-breakpoint
CREATE INDEX "battles_characterId_createdAt_idx" ON "battles" ("characterId","createdAt");--> statement-breakpoint
CREATE INDEX "battles_public_createdAt_idx" ON "battles" ("public","createdAt");--> statement-breakpoint
CREATE INDEX "battles_id_idx" ON "battles" ("id");--> statement-breakpoint
CREATE UNIQUE INDEX "user_characters_userId_characterId_world_key" ON "user_characters" ("userId","characterId","world");--> statement-breakpoint
CREATE INDEX "user_characters_userId_idx" ON "user_characters" ("userId");--> statement-breakpoint
ALTER TABLE "battle_warriors" ADD CONSTRAINT "battle_warriors_battleId_battles_id_fkey" FOREIGN KEY ("battleId") REFERENCES "battles"("id") ON DELETE CASCADE;