// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"0f5340b26743b0f07f6f8f30835b1c789b964d3a72a52272cf1a88ab01ea7cd2">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Activity: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly _type: "CONNECT_EVENT" | "DISCONNECT_EVENT";
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly details: CodecTypes["pg/jsonb@1"]["output"] | null;
      readonly actorSnapshotId: CodecTypes["pg/text@1"]["output"] | null;
      readonly world: CodecTypes["pg/text@1"]["output"] | null;
      readonly idempotencyKey: CodecTypes["pg/text@1"]["output"];
    };
    readonly ActivityActorSnapshot: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly accountId: CodecTypes["pg/int4@1"]["output"];
      readonly characterId: CodecTypes["pg/int4@1"]["output"];
      readonly clanName: CodecTypes["pg/text@1"]["output"] | null;
      readonly icon: CodecTypes["pg/text@1"]["output"];
      readonly lvl: CodecTypes["pg/int4@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly fingerprint: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly clanId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly prof: CodecTypes["pg/text@1"]["output"];
    };
    readonly MemberActivitySession: {
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly sessionId: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"] | null;
      readonly userAgent: CodecTypes["pg/text@1"]["output"] | null;
      readonly world: CodecTypes["pg/text@1"]["output"] | null;
      readonly connectedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly lastSeenAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly MemberActivityStats: {
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly lastSeenAt:
        | CodecTypes["pg/timestamptz-temporal@1"]["output"]
        | null;
      readonly visitCount: CodecTypes["pg/int4@1"]["output"];
      readonly activeSessionCount: CodecTypes["pg/int4@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Activity: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly _type: "CONNECT_EVENT" | "DISCONNECT_EVENT";
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly details: CodecTypes["pg/jsonb@1"]["input"] | null;
      readonly actorSnapshotId: CodecTypes["pg/text@1"]["input"] | null;
      readonly world: CodecTypes["pg/text@1"]["input"] | null;
      readonly idempotencyKey: CodecTypes["pg/text@1"]["input"];
    };
    readonly ActivityActorSnapshot: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly accountId: CodecTypes["pg/int4@1"]["input"];
      readonly characterId: CodecTypes["pg/int4@1"]["input"];
      readonly clanName: CodecTypes["pg/text@1"]["input"] | null;
      readonly icon: CodecTypes["pg/text@1"]["input"];
      readonly lvl: CodecTypes["pg/int4@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly fingerprint: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly clanId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly prof: CodecTypes["pg/text@1"]["input"];
    };
    readonly MemberActivitySession: {
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly sessionId: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"] | null;
      readonly userAgent: CodecTypes["pg/text@1"]["input"] | null;
      readonly world: CodecTypes["pg/text@1"]["input"] | null;
      readonly connectedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly lastSeenAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly MemberActivityStats: {
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly lastSeenAt:
        | CodecTypes["pg/timestamptz-temporal@1"]["input"]
        | null;
      readonly visitCount: CodecTypes["pg/int4@1"]["input"];
      readonly activeSessionCount: CodecTypes["pg/int4@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Activity: {
      readonly actorSnapshotId: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly details: CodecTypes["pg/jsonb@1"]["output"] | null;
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly idempotencyKey: CodecTypes["pg/text@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly type: "CONNECT_EVENT" | "DISCONNECT_EVENT";
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly world: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly ActivityActorSnapshot: {
      readonly accountId: CodecTypes["pg/int4@1"]["output"];
      readonly characterId: CodecTypes["pg/int4@1"]["output"];
      readonly clanId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly clanName: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly fingerprint: CodecTypes["pg/text@1"]["output"];
      readonly icon: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly lvl: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly prof: CodecTypes["pg/text@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
    };
    readonly MemberActivitySession: {
      readonly connectedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly lastSeenAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly sessionId: CodecTypes["pg/text@1"]["output"];
      readonly source: "GAME" | "WEB_APP";
      readonly userAgent: CodecTypes["pg/text@1"]["output"] | null;
      readonly userId: CodecTypes["pg/text@1"]["output"] | null;
      readonly world: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly MemberActivityStats: {
      readonly activeSessionCount: CodecTypes["pg/int4@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly discordId: CodecTypes["pg/text@1"]["output"];
      readonly guildId: CodecTypes["pg/text@1"]["output"];
      readonly lastSeenAt:
        | CodecTypes["pg/timestamptz-temporal@1"]["output"]
        | null;
      readonly source: "GAME" | "WEB_APP";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly visitCount: CodecTypes["pg/int4@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Activity: {
      readonly actorSnapshotId: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly details: CodecTypes["pg/jsonb@1"]["input"] | null;
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly idempotencyKey: CodecTypes["pg/text@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly type: "CONNECT_EVENT" | "DISCONNECT_EVENT";
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly world: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly ActivityActorSnapshot: {
      readonly accountId: CodecTypes["pg/int4@1"]["input"];
      readonly characterId: CodecTypes["pg/int4@1"]["input"];
      readonly clanId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly clanName: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly fingerprint: CodecTypes["pg/text@1"]["input"];
      readonly icon: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly lvl: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly prof: CodecTypes["pg/text@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
    };
    readonly MemberActivitySession: {
      readonly connectedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly lastSeenAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly sessionId: CodecTypes["pg/text@1"]["input"];
      readonly source: "GAME" | "WEB_APP";
      readonly userAgent: CodecTypes["pg/text@1"]["input"] | null;
      readonly userId: CodecTypes["pg/text@1"]["input"] | null;
      readonly world: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly MemberActivityStats: {
      readonly activeSessionCount: CodecTypes["pg/int4@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly discordId: CodecTypes["pg/text@1"]["input"];
      readonly guildId: CodecTypes["pg/text@1"]["input"];
      readonly lastSeenAt:
        | CodecTypes["pg/timestamptz-temporal@1"]["input"]
        | null;
      readonly source: "GAME" | "WEB_APP";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly visitCount: CodecTypes["pg/int4@1"]["input"];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly Activity: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly guildId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly discordId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: "ActivityType";
                  readonly codecId: "pg/enum@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: "ActivityType" };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly source: {
                  readonly nativeType: "ActivitySource";
                  readonly codecId: "pg/enum@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
                readonly details: {
                  readonly nativeType: "jsonb";
                  readonly codecId: "pg/jsonb@1";
                  readonly nullable: true;
                };
                readonly actorSnapshotId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly world: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly idempotencyKey: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ["id", "createdAt"];
                readonly name: "Activity_pkey";
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "Activity_createdAt_guildId_idx";
                  readonly columns: readonly ["createdAt", "guildId"];
                  readonly unique: false;
                },
                {
                  readonly name: "Activity_createdAt_type_idx";
                  readonly columns: readonly ["createdAt", "type"];
                  readonly unique: false;
                },
                {
                  readonly name: "Activity_createdAt_userId_idx";
                  readonly columns: readonly ["createdAt", "userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "Activity_guildId_createdAt_idx";
                  readonly columns: readonly ["guildId", "createdAt"];
                  readonly unique: false;
                },
                {
                  readonly name: "Activity_idempotencyKey_createdAt_key";
                  readonly columns: readonly ["idempotencyKey", "createdAt"];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "Activity";
                    readonly columns: readonly ["actorSnapshotId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "ActivityActorSnapshot";
                    readonly columns: readonly ["id"];
                  };
                  readonly name: "Activity_actorSnapshotId_fkey";
                },
              ];
            };
            readonly ActivityActorSnapshot: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly characterId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly clanName: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly icon: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly lvl: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: "ActivitySource";
                  readonly codecId: "pg/enum@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
                readonly fingerprint: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly clanId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly prof: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ["id"];
                readonly name: "ActivityActorSnapshot_pkey";
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "ActivityActorSnapshot_fingerprint_key";
                  readonly columns: readonly ["fingerprint"];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly MemberActivitySession: {
              columns: {
                readonly guildId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly discordId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: "ActivitySource";
                  readonly codecId: "pg/enum@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
                readonly sessionId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly userAgent: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly world: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly connectedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly lastSeenAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: {
                readonly columns: readonly [
                  "guildId",
                  "discordId",
                  "source",
                  "sessionId",
                ];
                readonly name: "MemberActivitySession_pkey";
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "MemberActivitySession_guildId_discordId_source_idx";
                  readonly columns: readonly ["guildId", "discordId", "source"];
                  readonly unique: false;
                },
                {
                  readonly name: "MemberActivitySession_guildId_source_idx";
                  readonly columns: readonly ["guildId", "source"];
                  readonly unique: false;
                },
                {
                  readonly name: "MemberActivitySession_lastSeenAt_idx";
                  readonly columns: readonly ["lastSeenAt"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly MemberActivityStats: {
              columns: {
                readonly guildId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly discordId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: "ActivitySource";
                  readonly codecId: "pg/enum@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
                readonly lastSeenAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: true;
                };
                readonly visitCount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/int4@1", 0>;
                  };
                };
                readonly activeSessionCount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/int4@1", 0>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ["guildId", "discordId", "source"];
                readonly name: "MemberActivityStats_pkey";
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "MemberActivityStats_guildId_source_idx";
                  readonly columns: readonly ["guildId", "source"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ActivitySource: {
              readonly kind: "valueSet";
              readonly values: readonly ["GAME", "WEB_APP"];
            };
            readonly ActivityType: {
              readonly kind: "valueSet";
              readonly values: readonly ["CONNECT_EVENT", "DISCONNECT_EVENT"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly ActivityActorSnapshot: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "ActivityActorSnapshot";
    };
    readonly Activity: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Activity";
    };
    readonly MemberActivitySession: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MemberActivitySession";
    };
    readonly MemberActivityStats: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MemberActivityStats";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Activity: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly guildId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly discordId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly _type: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/enum@1";
                  readonly typeParams: { readonly typeName: "ActivityType" };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/enum@1";
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
              };
              readonly details: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/jsonb@1";
                };
              };
              readonly actorSnapshotId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly world: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly idempotencyKey: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly actorSnapshot: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "ActivityActorSnapshot";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["actorSnapshotId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "Activity";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly guildId: { readonly column: "guildId" };
                readonly discordId: { readonly column: "discordId" };
                readonly _type: { readonly column: "type" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly source: { readonly column: "source" };
                readonly details: { readonly column: "details" };
                readonly actorSnapshotId: {
                  readonly column: "actorSnapshotId";
                };
                readonly world: { readonly column: "world" };
                readonly idempotencyKey: { readonly column: "idempotencyKey" };
              };
            };
          };
          readonly ActivityActorSnapshot: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly characterId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly clanName: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly icon: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly lvl: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/enum@1";
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
              };
              readonly fingerprint: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly clanId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly prof: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly activities: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Activity";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["actorSnapshotId"];
                };
              };
            };
            readonly storage: {
              readonly table: "ActivityActorSnapshot";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly accountId: { readonly column: "accountId" };
                readonly characterId: { readonly column: "characterId" };
                readonly clanName: { readonly column: "clanName" };
                readonly icon: { readonly column: "icon" };
                readonly lvl: { readonly column: "lvl" };
                readonly source: { readonly column: "source" };
                readonly fingerprint: { readonly column: "fingerprint" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly clanId: { readonly column: "clanId" };
                readonly name: { readonly column: "name" };
                readonly prof: { readonly column: "prof" };
              };
            };
          };
          readonly MemberActivitySession: {
            readonly fields: {
              readonly guildId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly discordId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/enum@1";
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly world: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly connectedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly lastSeenAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "MemberActivitySession";
              readonly namespaceId: "public";
              readonly fields: {
                readonly guildId: { readonly column: "guildId" };
                readonly discordId: { readonly column: "discordId" };
                readonly source: { readonly column: "source" };
                readonly sessionId: { readonly column: "sessionId" };
                readonly userId: { readonly column: "userId" };
                readonly userAgent: { readonly column: "userAgent" };
                readonly world: { readonly column: "world" };
                readonly connectedAt: { readonly column: "connectedAt" };
                readonly lastSeenAt: { readonly column: "lastSeenAt" };
              };
            };
          };
          readonly MemberActivityStats: {
            readonly fields: {
              readonly guildId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly discordId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/enum@1";
                  readonly typeParams: { readonly typeName: "ActivitySource" };
                };
              };
              readonly lastSeenAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly visitCount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly activeSessionCount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "MemberActivityStats";
              readonly namespaceId: "public";
              readonly fields: {
                readonly guildId: { readonly column: "guildId" };
                readonly discordId: { readonly column: "discordId" };
                readonly source: { readonly column: "source" };
                readonly lastSeenAt: { readonly column: "lastSeenAt" };
                readonly visitCount: { readonly column: "visitCount" };
                readonly activeSessionCount: {
                  readonly column: "activeSessionCount";
                };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
