namespace: lootlog-dev
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: dev-b533a8c2f86d147ae7cc01a0b4cfc94fe27fb103
namePrefix: dev-
