namespace: lootlog-dev
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: dev-4bfdef8a54f1c00b6050430af4418887fe00cabb
namePrefix: dev-
