namespace: lootlog-dev
resources:
  - ../../base/auth
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-auth
    newTag: dev-8eb712f9901cb08faf88077d2299b34222913a68
namePrefix: dev-
