export enum ErrorKey {
  EXISTING_TIMER = "EXISTING_TIMER",
  WT_TOO_LOW = "WT_TOO_LOW",
  BLACKLISTED_GUILD = "BLACKLISTED_GUILD",
  TIMER_NOT_FOUND = "TIMER_NOT_FOUND",
  TIMER_RACE_CONDITION = "TIMER_RACE_CONDITION",
  TIMER_UPDATE_CONFLICT = "TIMER_UPDATE_CONFLICT",
  INVALID_CUSTOM_SPAWN_TIME = "INVALID_CUSTOM_SPAWN_TIME",
  SPAWN_TIME_IN_PAST = "SPAWN_TIME_IN_PAST",
  SPAWN_WINDOW_TOO_LARGE = "SPAWN_WINDOW_TOO_LARGE",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  GUILD_NOT_WHITELISTED = "GUILD_NOT_WHITELISTED",
}
