import { MEMBER_DISCORD_SYNC_STATUS } from "../member-discord-sync-status.js";

export const MEMBER_LAST_DISCORD_STATUS = {
  ...MEMBER_DISCORD_SYNC_STATUS,
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  GUILD_DEACTIVATED: "GUILD_DEACTIVATED",
  GUILD_NOT_IN_DISCORD_LIST: "GUILD_NOT_IN_DISCORD_LIST",
  MANUALLY_DEACTIVATED: "MANUALLY_DEACTIVATED",
} as const;

export type MemberLastDiscordStatus =
  (typeof MEMBER_LAST_DISCORD_STATUS)[keyof typeof MEMBER_LAST_DISCORD_STATUS];
