export enum GatewayEvent {
  DISCONNECTING = 'disconnecting',
  INIT = 'init',
  JOIN = 'join',
  REQUEST_SERVER_PRESENCE = 'request-server-presence',
  UPDATE_SERVER_PRESENCE = 'update-server-presence',
  CHAT_MESSAGE = 'chat-message',
  TIMERS_CREATE = 'timers-create',
  TIMERS_DELETE = 'timers-delete',
  RESERVATIONS_CREATE = 'reservations-create',
  RESERVATIONS_DELETE = 'reservations-delete',
  NOTIFICATIONS_SEND = 'notifications-send',
  MEMBERS_REFRESH_JOB_UPDATE = 'members-refresh-job-update',
  PERMISSIONS_UPDATED = 'permissions-updated',
  EVENT_PRESENCE_UPDATE = 'event:presence:update',
  EVENT_MAP_STATUS_UPDATE = 'event:map-status:update',
  EVENT_HERO_KILLED = 'event:hero:killed',
  EVENT_RANKING_UPDATE = 'event:ranking:update',
}
