export enum GatewayEvent {
  DISCONNECTING = "disconnecting",
  INIT = "init",
  JOIN = "join",
  ONLINE_PLAYERS_PRESENCE_FETCH = "online-players:presence:fetch",
  ONLINE_PLAYERS_PRESENCE_UPDATE = "online-players:presence:update",
  MEMBER_WEB_PRESENCE_FETCH = "member-web-presence:fetch",
  MEMBER_WEB_PRESENCE_UPDATE = "member-web-presence:update",
  CHAT_MESSAGE = "chat-message",
  LOOTS_CREATE = "loots-create",
  LOOTS_SHARE_UPDATE = "loots-share-update",
  TIMERS_CREATE = "timers-create",
  TIMERS_DELETE = "timers-delete",
  RESERVATIONS_CREATE = "reservations-create",
  RESERVATIONS_DELETE = "reservations-delete",
  NOTIFICATIONS_SEND = "notifications-send",
  NOTIFICATIONS_VOLUNTEER = "notifications-volunteer",
  PARTY_GATHERING_SEND = "party-gathering-send",
  PARTY_GATHERING_CANCEL = "party-gathering-cancel",
  CHAT_MESSAGE_DELETE = "chat-message-delete",
  CHAT_MESSAGE_UPDATE = "chat-message-update",
  CHAT_MESSAGES_CLEAR = "chat-messages-clear",
  MEMBERS_REFRESH_JOB_UPDATE = "members-refresh-job-update",
  PERMISSIONS_UPDATED = "permissions-updated",
  MAP_PING_SEND = "map-ping:send",
  MAP_PING_RECEIVE = "map-ping:receive",

  // Presence events
  PLAYER_PRESENCE_UPDATE = "player-presence:update",
  EVENT_PRESENCE_UPDATE = "event-presence:update",
  EVENT_PRESENCE_FETCH = "event-presence:fetch",

  // Margo event-specific events
  EVENT_MAP_STATUS_UPDATE = "event:map-status:update",
  EVENT_HERO_KILLED = "event:hero:killed",
  EVENT_RANKING_UPDATE = "event:ranking:update",
  EVENT_RESPAWN_WINDOW_OPENED = "event:respawn-window:opened",
  EVENT_RESPAWN_WINDOW_CLOSED = "event:respawn-window:closed",
}
