import type {
  NotificationStoredTarget,
  NotificationStoredJob,
  NotificationStoredRule,
} from "../src/notifications/jobs/notification-job-store.js";

export const createNotificationJobFixture = (
  overrides: Partial<NotificationStoredJob> = {},
): NotificationStoredJob => ({
  id: "job-1",
  ruleId: 7,
  targetId: 9,
  ownerType: "USER",
  ownerId: "user-1",
  jobKind: "INSTANT",
  status: "PROCESSING",
  scheduledFor: new Date(0),
  idempotencyKey: "job-1",
  sourceEntityType: "loot",
  sourceEntityId: null,
  sourceEventId: null,
  payloadSnapshot: {},
  attemptCount: 1,
  lastError: null,
  blockedReason: null,
  providerMessageId: null,
  processedAt: null,
  createdAt: new Date(0),
  updatedAt: new Date(0),
  ...overrides,
});

export const createNotificationRuleFixture = (
  overrides: Partial<NotificationStoredRule> = {},
): NotificationStoredRule => ({
  id: 7,
  ownerType: "USER",
  ownerId: "user-1",
  triggerType: "SCHEDULED_MESSAGE",
  guildId: null,
  world: null,
  name: null,
  filters: {},
  contentTemplate: null,
  scheduleStrategy: "FIXED_DATETIME",
  scheduleAnchor: null,
  scheduleOffsetMinutes: null,
  scheduledAt: new Date("2026-09-02T12:00:00.000Z"),
  scheduleIntervalType: "DAILY",
  scheduleIntervalValue: 1,
  scheduleWeekday: null,
  scheduleTimeOfDay: "12:00",
  scheduledUntil: null,
  scheduleTimezone: "Europe/Warsaw",
  enabled: true,
  dedupeWindowSeconds: 0,
  createdAt: new Date(0),
  updatedAt: new Date(0),
  ...overrides,
});

export const createNotificationTargetFixture = (
  overrides: Partial<NotificationStoredTarget> = {},
): NotificationStoredTarget => ({
  id: 9,
  ownerType: "USER",
  ownerId: "user-1",
  provider: "DISCORD",
  targetType: "DM",
  externalId: "user-1",
  displayName: null,
  guildName: null,
  metadata: null,
  active: true,
  canSend: true,
  lastSyncedAt: null,
  lastDeliveryAt: null,
  lastDeliveryError: null,
  createdAt: new Date(0),
  updatedAt: new Date(0),
  ...overrides,
});
