apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth
      containers:
        - name: auth
          image: kamilwronka7/lootlog-auth:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1.5Gi"
              cpu: "2000m"

          ports:
            - name: container-port
              containerPort: 4000

          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1200"

            - name: PORT
              value: "4000"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-auth-secrets
            - name: SERVICE_NAME
              value: auth
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: postgresqlPort
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: postgresqlHost
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: postgresqlDatabase
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: postgresqlUsername
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: postgresqlPassword
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: discordClientSecret
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: discordClientId
            - name: TRUSTED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: trustedOrigins
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: appUrl
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: cookieDomain
            - name: COOKIE_PREFIX
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: cookiePrefix
            - name: ADMIN_ACCOUNT_IDS
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: adminAccountIds
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: rabbitmqUri
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: otelExporterOtlpEndpoint
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: otelExporterOtlpHeaders
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: "env,host,os,process"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: SERVICE_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: lootlog-auth-secrets
                  key: serviceNamespace

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 3
