apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      serviceAccountName: discord-bot
      containers:
        - name: discord-bot
          image: kamilwronka7/lootlog-discord-bot:latest
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '384Mi'
              cpu: '300m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: env
                  name: lootlog-discord-bot-secrets
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lootlog-discord-bot-secrets
                  key: discordBotToken
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: lootlog-discord-bot-secrets
                  key: rabbitmqUri

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
