apiVersion: v1
kind: Service
metadata:
  name: discord-bot
  labels:
    app: discord-bot
    service: discord-bot
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: discord-bot
