namespace: lootlog-prod
resources:
  - ../../base/battlelog-service
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-battlelog-service
    newTag: prod-3259149b195e22fdd53a697a441bce4ae72fb2e3
namePrefix: prod-
