namespace: lootlog-prod
resources:
  - ../../base/battlelog-service
patchesStrategicMerge:
  - hpa.yml
images:
  - name: kamilwronka7/lootlog-battlelog-service
    newTag: prod-1007933f7d50dd70569bf4b21243d21334409794
namePrefix: prod-
