FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /usr/src/app

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm i

COPY . .

EXPOSE 4000

ENTRYPOINT [ "pnpm", "start:dev" ]