name: Deploy Battlelog Service to dev
permissions:
  contents: write
  security-events: write

on:
  push:
    paths:
      - "apps/battlelog-service/**"
      - "packages/**"
      - ".github/workflows/dev-deploy-battlelog-service.yml"
      - ".github/workflows/deploy-service.yml"
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: deploy-battlelog-service-dev
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service: battlelog-service
      environment: dev
      enable_notifications: false
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
