name: Deploy Developer Portal to dev
permissions:
  contents: write
  security-events: write

on:
  push:
    paths:
      - "apps/developer/**"
      - "packages/**"
      - ".github/workflows/dev-deploy-developer.yml"
      - ".github/workflows/deploy-service.yml"
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: deploy-developer-dev
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service: developer
      environment: dev
      enable_notifications: false
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      INFRA_REPO_PUSH_TOKEN: ${{ secrets.INFRA_REPO_PUSH_TOKEN }}
