name: Deploy API to prod

on:
  workflow_dispatch:

concurrency:
  group: deploy-api-prod
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service: api
      environment: prod
      enable_notifications: false
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
